shell:
  - '**.sh'
  - .github/workflows/shellcheck.yaml
sql:
  - 'sql/**'
  - '.github/**'
src:
  - 'CMakeLists.txt'
  - 'cmake/**'
  - 'coverage/**'
  - 'scripts/**'
  - 'sql/**'
  - 'src/**'
  - 'test/**'
  - 'tsl/**'
  - '.github/**'
