\ir ../../meta/cluster.sql
\ir ../../meta/node_triggers.sql
\ir ../../meta/chunk_triggers.sql
\ir ../../meta/chunk_replica_node_triggers.sql
\ir ../../meta/default_replica_node.sql
\ir ../../meta/chunk.sql
\ir ../../meta/hypertable_triggers.sql
\ir ../../meta/partition_triggers.sql
\ir ../../meta/sync_triggers.sql
\ir ../../meta/setup_meta.sql
\ir ../../meta/deleted_triggers.sql
\ir ../../meta/ddl.sql
