\ir ../../main/table_creation.sql
\ir ../../main/tables.sql
\ir ../../main/cluster_user_triggers.sql
\ir ../../main/node_triggers.sql
\ir ../../main/meta_triggers.sql
\ir ../../main/hypertable_triggers.sql
\ir ../../main/hypertable_index_triggers.sql
\ir ../../main/hypertable_replica_triggers.sql
\ir ../../main/field_triggers.sql
\ir ../../main/partitioning.sql
\ir ../../main/schema_info.sql
\ir ../../main/partition_replica_triggers.sql
\ir ../../main/chunk_replica_node_index.sql
\ir ../../main/chunk_replica_node_index_triggers.sql
\ir ../../main/chunk_replica_node_triggers.sql
\ir ../../main/chunk_triggers.sql
\ir ../../main/chunk.sql
\ir ../../main/insert.sql
\ir ../../main/meta_info.sql
\ir ../../main/ddl_util.sql
\ir ../../main/ddl.sql
\ir ../../main/ddl_triggers.sql

\ir ../../main/setup_main.sql
