/*
 * This file and its contents are licensed under the Timescale License.
 * Please see the included NOTICE for copyright information and
 * LICENSE-TIMESCALE for a copy of the license.
 */
#include <postgres.h>
#include <utils/memutils.h>
#include <utils/palloc.h>
#include <utils/snapmgr.h>
#include <utils/tuplestore.h>
#include <nodes/memnodes.h>
#include <storage/lockdefs.h>
#include <access/htup_details.h>
#include <access/htup.h>
#include <access/xact.h>
#include <miscadmin.h>

#include <catalog.h>
#include <scanner.h>
#include <scan_iterator.h>
#include <utils.h>
#include <errors.h>

#include "continuous_agg.h"
#include "continuous_aggs/materialize.h"
#include "invalidation.h"

/*
 * Invalidation processing for continuous aggregates.
 *
 * Invalidations track the regions/intervals [start, end] of a continuous
 * aggregate that are out-of-date relative the source hypertable on top of
 * which the aggregate is defined. When a continuous aggregate is out-of-date
 * across one or more regions, it can be refreshed with a window covering
 * those regions in order to bring it up-to-date with the source data again.
 *
 * Invalidations are generated by mutations on the source hypertable (INSERT,
 * DELETE, UPDATE, TRUNCATE, drop_chunks, etc.) and are initially written to a
 * hypertable invalidation log [hypertable_id, start, end].
 *
 * When a continuous aggregate is refreshed, invalidations are moved from the
 * hypertable invalidation log to a continuous aggregate invalidation log,
 * where each original entry creates one new entry per continuous aggregate
 * [cagg_id, start, end]. Thus, if one continuous aggregate is refreshed but
 * not others, then only the invalidations for the refreshed aggregate are
 * processed.
 *
 * Simplified, invalidations move through the following stages:
 *
 * insert_trigger => hypertable_inval_log => cagg_inval_log => refreshing
 *
 * Thus, invalidations are generated by mutations and are processed and used
 * as input for refreshing the a continuous aggregate.
 *
 * Invalidations can overlap or be duplicates. Therefore, invalidations are
 * merged during processing to reduce the number of entries in the logs. This
 * typically happens during a refresh of a continuous aggregate, which also
 * cuts invalidations along the refresh window. The cutting will leave some
 * parts of entries in the ivnalidation log while the entries that fall within
 * the refresh window are stored in an invalidation store and used for
 * refreshing:
 *
 *       |-------------|    refresh window
 *
 *   |-----|  |---| |----|  invalidations
 *
 *             =>
 *
 *   |---|             |--| invalidations that remain in the log
 *
 *       |-|  |---| |--|    invalidations that are used for refreshing
 *
 * The invalidation store will spill to disk in case of many invalidations so
 * it won't blow up memory usage. If there are no invalidations in the store
 * after processing, then the continuous aggregate is up-to-date in the region
 * defined by the refresh window.
 */

typedef struct CaggInvalidationState
{
	ContinuousAgg cagg;
	MemoryContext per_tuple_mctx;
	Relation cagg_log_rel;
	Snapshot snapshot;
	Tuplestorestate *invalidations;
} CaggInvalidationState;

typedef enum LogType
{
	LOG_HYPER,
	LOG_CAGG,
} LogType;

static void cagg_invalidations_scan_by_hypertable_and_frozen_init(ScanIterator *iterator,
																  int32 cagg_hyper_id, int64 end,
																  bool frozen, LOCKMODE lockmode);
static void invalidation_entry_reset(Invalidation *entry);
static void invalidation_entry_set_from_cagg_invalidation(Invalidation *entry, const TupleInfo *ti);

static Relation
open_invalidation_log(LogType type, LOCKMODE lockmode)
{
	static const CatalogTable logmappings[] = {
		[LOG_HYPER] = CONTINUOUS_AGGS_HYPERTABLE_INVALIDATION_LOG,
		[LOG_CAGG] = CONTINUOUS_AGGS_MATERIALIZATION_INVALIDATION_LOG,
	};
	Catalog *catalog = ts_catalog_get();
	Oid relid = catalog_get_table_id(catalog, logmappings[type]);

	return table_open(relid, lockmode);
}

static void
invalidation_state_init(CaggInvalidationState *state, const ContinuousAgg *cagg)
{
	MemSet(state, 0, sizeof(*state));

	if (cagg)
		state->cagg = *cagg;

	state->cagg_log_rel = open_invalidation_log(LOG_CAGG, RowExclusiveLock);
	state->per_tuple_mctx = AllocSetContextCreate(CurrentMemoryContext,
												  "Continuous aggregate invalidations",
												  ALLOCSET_DEFAULT_SIZES);
	state->snapshot = RegisterSnapshot(GetTransactionSnapshot());
}

static void
invalidation_state_cleanup(const CaggInvalidationState *state)
{
	table_close(state->cagg_log_rel, NoLock);
	UnregisterSnapshot(state->snapshot);
	MemoryContextDelete(state->per_tuple_mctx);
}

/*
 * Check if two invalidations can be merged into one.
 *
 * Since invalidations are inclusive in both ends, two adjacent invalidations
 * can be merged.
 */
static bool
invalidations_can_be_merged(const Invalidation *a, const Invalidation *b)
{
	/* To account for adjacency, expand one window 1 step in each
	 * direction. This makes adjacent invalidations overlapping. */
	int64 a_start = int64_saturating_sub(a->lowest_modified_value, 1);
	int64 a_end = int64_saturating_add(a->greatest_modified_value, 1);

	return a_end >= b->lowest_modified_value && a_start <= b->greatest_modified_value;
}

static void
cagg_scan_by_hypertable_init(ScanIterator *iterator, int32 hyper_id, LOCKMODE lockmode)
{
	*iterator = ts_scan_iterator_create(CONTINUOUS_AGG, lockmode, CurrentMemoryContext);
	iterator->ctx.index =
		catalog_get_index(ts_catalog_get(), CONTINUOUS_AGG, CONTINUOUS_AGG_RAW_HYPERTABLE_ID_IDX);
	ts_scan_iterator_scan_key_init(iterator,
								   Anum_continuous_agg_raw_hypertable_id_idx_raw_hypertable_id,
								   BTEqualStrategyNumber,
								   F_INT4EQ,
								   Int32GetDatum(hyper_id));
}

/*
 * Get a list of continuous aggregate IDs for a hypertable.
 *
 * Since this is just an integer list, the memory cost is not big even if
 * there are a lot of continuous aggregates.
 */
static List *
get_cagg_ids(int32 hyper_id)
{
	List *cagg_ids = NIL;
	ScanIterator iterator;

	cagg_scan_by_hypertable_init(&iterator, hyper_id, AccessShareLock);

	ts_scanner_foreach(&iterator)
	{
		bool isnull;
		TupleInfo *ti_cagg = ts_scan_iterator_tuple_info(&iterator);
		Datum cagg_hyper_id =
			slot_getattr(ti_cagg->slot, Anum_continuous_agg_mat_hypertable_id, &isnull);
		Assert(!isnull);
		cagg_ids = lappend_int(cagg_ids, DatumGetInt32(cagg_hyper_id));
	}

	ts_scan_iterator_close(&iterator);

	return cagg_ids;
}

static void
hypertable_invalidation_scan_init(ScanIterator *iterator, int32 hyper_id, LOCKMODE lockmode)
{
	*iterator = ts_scan_iterator_create(CONTINUOUS_AGGS_HYPERTABLE_INVALIDATION_LOG,
										lockmode,
										CurrentMemoryContext);
	iterator->ctx.index = catalog_get_index(ts_catalog_get(),
											CONTINUOUS_AGGS_HYPERTABLE_INVALIDATION_LOG,
											CONTINUOUS_AGGS_HYPERTABLE_INVALIDATION_LOG_IDX);
	ts_scan_iterator_scan_key_init(
		iterator,
		Anum_continuous_aggs_hypertable_invalidation_log_idx_hypertable_id,
		BTEqualStrategyNumber,
		F_INT4EQ,
		Int32GetDatum(hyper_id));
}

static HeapTuple
create_invalidation_tup(const TupleDesc tupdesc, int32 cagg_hyper_id, int64 modtime, int64 start,
						int64 end, bool frozen)
{
	Datum values[Natts_continuous_aggs_materialization_invalidation_log] = { 0 };
	bool isnull[Natts_continuous_aggs_materialization_invalidation_log] = { false };

	values[AttrNumberGetAttrOffset(
		Anum_continuous_aggs_materialization_invalidation_log_materialization_id)] =
		Int32GetDatum(cagg_hyper_id);
	values[AttrNumberGetAttrOffset(
		Anum_continuous_aggs_materialization_invalidation_log_modification_time)] =
		Int64GetDatum(modtime);
	values[AttrNumberGetAttrOffset(
		Anum_continuous_aggs_materialization_invalidation_log_lowest_modified_value)] =
		Int64GetDatum(start);
	values[AttrNumberGetAttrOffset(
		Anum_continuous_aggs_materialization_invalidation_log_greatest_modified_value)] =
		Int64GetDatum(end);
	values[AttrNumberGetAttrOffset(Anum_continuous_aggs_materialization_invalidation_log_frozen)] =
		BoolGetDatum(frozen);

	return heap_form_tuple(tupdesc, values, isnull);
}

/*
 * Add an entry to the continuous aggregate invalidation log.
 */
void
invalidation_cagg_log_add_entry(int32 cagg_hyper_id, int64 modtime, int64 start, int64 end,
								bool frozen)
{
	CatalogSecurityContext sec_ctx;
	CaggInvalidationState state;
	HeapTuple tuple;
	Invalidation mergedentry;
	ScanIterator iterator;
	int64 overlapping_end;

	/* We want to merge the new invalidation--not only with those existing
	 * invalidations that are overlapping--but also adjacent ones since
	 * invalidations are inclusive in both ends. To include adjacent ones in
	 * the scan, we need to add one to the end value to make it seem like
	 * there's an overlap. */
	overlapping_end = int64_saturating_add(end, 1);

	Assert(start <= end);
	invalidation_state_init(&state, NULL);
	invalidation_entry_reset(&mergedentry);
	cagg_invalidations_scan_by_hypertable_and_frozen_init(&iterator,
														  cagg_hyper_id,
														  overlapping_end,
														  frozen,
														  RowExclusiveLock);
	iterator.ctx.snapshot = state.snapshot;

	MemoryContextReset(state.per_tuple_mctx);

	mergedentry.hyper_id = cagg_hyper_id;
	mergedentry.modification_time = modtime;
	mergedentry.lowest_modified_value = start;
	mergedentry.greatest_modified_value = end;
	mergedentry.frozen = frozen;

	/* Process all invalidations for the continuous aggregate */
	ts_scanner_foreach(&iterator)
	{
		TupleInfo *ti = ts_scan_iterator_tuple_info(&iterator);
		MemoryContext oldmctx;
		Invalidation logentry;

		oldmctx = MemoryContextSwitchTo(state.per_tuple_mctx);
		invalidation_entry_set_from_cagg_invalidation(&logentry, ti);

		Assert(mergedentry.frozen == logentry.frozen);

		if (!invalidations_can_be_merged(&mergedentry, &logentry))
		{
			/* If no merging can be performed, then we are done */
			MemoryContextSwitchTo(oldmctx);
			ts_scan_iterator_close(&iterator);
			break;
		}

		if (logentry.greatest_modified_value > mergedentry.greatest_modified_value)
			mergedentry.greatest_modified_value = logentry.greatest_modified_value;

		if (logentry.lowest_modified_value < mergedentry.lowest_modified_value)
			mergedentry.lowest_modified_value = logentry.lowest_modified_value;

		/* The previous and current invalidation were merged into
		 * one entry (i.e., they overlapped or were adjacent).
		 */
		ts_catalog_delete_tid_only(state.cagg_log_rel, &logentry.tid);
		MemoryContextSwitchTo(oldmctx);
		MemoryContextReset(state.per_tuple_mctx);
	}

	tuple = create_invalidation_tup(RelationGetDescr(state.cagg_log_rel),
									mergedentry.hyper_id,
									mergedentry.modification_time,
									mergedentry.lowest_modified_value,
									mergedentry.greatest_modified_value,
									mergedentry.frozen);
	ts_catalog_database_info_become_owner(ts_catalog_database_info_get(), &sec_ctx);
	ts_catalog_insert_only(state.cagg_log_rel, tuple);
	ts_catalog_restore_user(&sec_ctx);
	heap_freetuple(tuple);
	invalidation_state_cleanup(&state);
}

void
invalidation_hyper_log_add_entry(int32 hyper_id, int64 modtime, int64 start, int64 end)
{
	Relation rel = open_invalidation_log(LOG_HYPER, RowExclusiveLock);
	CatalogSecurityContext sec_ctx;
	Datum values[Natts_continuous_aggs_hypertable_invalidation_log];
	bool nulls[Natts_continuous_aggs_hypertable_invalidation_log] = { false };

	Assert(start <= end);
	values[AttrNumberGetAttrOffset(
		Anum_continuous_aggs_hypertable_invalidation_log_hypertable_id)] = Int32GetDatum(hyper_id);
	values[AttrNumberGetAttrOffset(
		Anum_continuous_aggs_hypertable_invalidation_log_modification_time)] =
		Int64GetDatum(modtime);
	values[AttrNumberGetAttrOffset(
		Anum_continuous_aggs_hypertable_invalidation_log_lowest_modified_value)] =
		Int64GetDatum(start);
	values[AttrNumberGetAttrOffset(
		Anum_continuous_aggs_hypertable_invalidation_log_greatest_modified_value)] =
		Int64GetDatum(end);

	ts_catalog_database_info_become_owner(ts_catalog_database_info_get(), &sec_ctx);
	ts_catalog_insert_values(rel, RelationGetDescr(rel), values, nulls);
	ts_catalog_restore_user(&sec_ctx);
	table_close(rel, NoLock);
}

static void
cagg_invalidations_scan_by_hypertable_init(ScanIterator *iterator, int32 cagg_hyper_id,
										   LOCKMODE lockmode)
{
	*iterator = ts_scan_iterator_create(CONTINUOUS_AGGS_MATERIALIZATION_INVALIDATION_LOG,
										lockmode,
										CurrentMemoryContext);
	iterator->ctx.index = catalog_get_index(ts_catalog_get(),
											CONTINUOUS_AGGS_MATERIALIZATION_INVALIDATION_LOG,
											CONTINUOUS_AGGS_MATERIALIZATION_INVALIDATION_LOG_IDX);
	ts_scan_iterator_scan_key_init(
		iterator,
		Anum_continuous_aggs_materialization_invalidation_log_idx_materialization_id,
		BTEqualStrategyNumber,
		F_INT4EQ,
		Int32GetDatum(cagg_hyper_id));
}

/*
 * Initialize a scan for invalidations that match the hypertable ID and frozen
 * flag. Additionally, do not return invalidations that we know are not
 * overlapping with the given "end" value.
 */
static void
cagg_invalidations_scan_by_hypertable_and_frozen_init(ScanIterator *iterator, int32 cagg_hyper_id,
													  int64 end, bool frozen, LOCKMODE lockmode)
{
	cagg_invalidations_scan_by_hypertable_init(iterator, cagg_hyper_id, lockmode);

	ts_scan_iterator_scan_key_init(
		iterator,
		Anum_continuous_aggs_materialization_invalidation_log_idx_lowest_modified_value,
		BTLessEqualStrategyNumber,
		F_INT8LE,
		Int64GetDatum(end));

	ts_scan_iterator_scan_key_init(iterator,
								   Anum_continuous_aggs_materialization_invalidation_log_idx_frozen,
								   BTEqualStrategyNumber,
								   F_BOOLEQ,
								   BoolGetDatum(frozen));
}

static void
invalidation_entry_reset(Invalidation *entry)
{
	MemSet(entry, 0, sizeof(Invalidation));
}

/*
 * Invalidate one or more continuous aggregates.
 *
 * Add an invalidation in the given range. The invalidation is added either to
 * the hypertable invalidation log or the continuous aggregate invalidation
 * log depending on the type of the given hypertable. If the hypertable is a
 * "raw" hypertable (i.e., one that has one or more continous aggregates), the
 * entry is added to the hypertable invalidation log and will invalidate all
 * the associated continuous aggregates. If the hypertable is instead an
 * materialized hypertable, the entry is added to the cagg invalidation log
 * and only invalidates the continuous aggregate owning that materialized
 * hypertable.
 */
void
invalidation_add_entry(const Hypertable *ht, int64 start, int64 end)
{
	ContinuousAggHypertableStatus caggstatus;
	Dimension *dim;
	int64 timeval;

	Assert(ht != NULL);
	caggstatus = ts_continuous_agg_hypertable_status(ht->fd.id);

	switch (caggstatus)
	{
		case HypertableIsMaterialization:
		{
			ContinuousAgg *cagg = ts_continuous_agg_find_by_mat_hypertable_id(ht->fd.id);
			Hypertable *raw_ht;

			/* Need to get the now function from the "raw" hypertable */
			Assert(NULL != cagg);
			raw_ht = ts_hypertable_get_by_id(cagg->data.raw_hypertable_id);
			dim = hyperspace_get_open_dimension(raw_ht->space, 0);
			timeval = ts_get_now_internal(dim);
			invalidation_cagg_log_add_entry(ht->fd.id, timeval, start, end, false);
			break;
		}
		case HypertableIsRawTable:
			dim = hyperspace_get_open_dimension(ht->space, 0);
			timeval = ts_get_now_internal(dim);
			invalidation_hyper_log_add_entry(ht->fd.id, timeval, start, end);
			break;
		case HypertableIsMaterializationAndRaw:
			break;
		case HypertableIsNotContinuousAgg:
			ereport(ERROR,
					(errcode(ERRCODE_WRONG_OBJECT_TYPE),
					 errmsg("cannot add invalidation for hypertable \"%s\"",
							get_rel_name(ht->main_table_relid)),
					 errdetail("There is no continuous aggregate associated with the hypertable")));
			break;
	}
}

typedef enum InvalidationResult
{
	INVAL_NOMATCH,
	INVAL_DELETE,
	INVAL_CUT,
} InvalidationResult;

#define IS_VALID_INVALIDATION(entry) ((entry)->hyper_id > 0)

static bool
save_invalidation_for_refresh(const CaggInvalidationState *state, const Invalidation *invalidation)
{
	int32 cagg_hyper_id = state->cagg.data.mat_hypertable_id;
	TupleDesc tupdesc = RelationGetDescr(state->cagg_log_rel);
	HeapTuple refresh_tup;

	if (!IS_VALID_INVALIDATION(invalidation) || state->invalidations == NULL)
		return false;

	refresh_tup = create_invalidation_tup(tupdesc,
										  cagg_hyper_id,
										  invalidation->modification_time,
										  invalidation->lowest_modified_value,
										  invalidation->greatest_modified_value,
										  invalidation->frozen);
	tuplestore_puttuple(state->invalidations, refresh_tup);
	heap_freetuple(refresh_tup);

	return true;
}

static void
set_remainder_after_cut(Invalidation *remainder, int32 hyper_id, int64 modification_time,
						int64 lowest_modified_value, int64 greatest_modified_value)
{
	MemSet(remainder, 0, sizeof(*remainder));
	remainder->hyper_id = hyper_id;
	remainder->modification_time = modification_time;
	remainder->lowest_modified_value = lowest_modified_value;
	remainder->greatest_modified_value = greatest_modified_value;
}

/*
 * Try to cut an invalidation against the refresh window.
 *
 * If an invalidation entry overlaps with the refresh window, it needs
 * additional processing: it is either cut, deleted, or left unmodified.
 *
 * The part(s) of the invalidation that are outside the refresh window after
 * the cut will remain in the log. The part of the invalidation that fits
 * within the window is returned as the "remainder".
 *
 * Note that the refresh window is exclusive in the end while invalidations
 * are inclusive.
 */
static InvalidationResult
cut_invalidation_along_refresh_window(const CaggInvalidationState *state,
									  const Invalidation *invalidation,
									  const InternalTimeRange *refresh_window,
									  Invalidation *remainder)
{
	int32 cagg_hyper_id = state->cagg.data.mat_hypertable_id;
	TupleDesc tupdesc = RelationGetDescr(state->cagg_log_rel);
	InvalidationResult result = INVAL_NOMATCH;
	HeapTuple lower = NULL;
	HeapTuple upper = NULL;

	Assert(remainder != NULL);

	/* Entry is completely enclosed by the refresh window */
	if (invalidation->lowest_modified_value >= refresh_window->start &&
		invalidation->greatest_modified_value < refresh_window->end)
	{
		/*

		 * Entry completely enclosed so can be deleted:
		 *
		 * |---------------|
		 *     [+++++]
		 */

		result = INVAL_DELETE;
		set_remainder_after_cut(remainder,
								cagg_hyper_id,
								invalidation->modification_time,
								invalidation->lowest_modified_value,
								invalidation->greatest_modified_value);
	}
	else
	{
		if (invalidation->lowest_modified_value < refresh_window->start &&
			invalidation->greatest_modified_value >= refresh_window->start)
		{
			/*
			 * Need to cut in right end:
			 *
			 *     |------|
			 * [++++++]
			 *
			 * [++]
			 */
			lower = create_invalidation_tup(tupdesc,
											cagg_hyper_id,
											invalidation->modification_time,
											invalidation->lowest_modified_value,
											refresh_window->start - 1,
											invalidation->frozen);
			set_remainder_after_cut(remainder,
									cagg_hyper_id,
									invalidation->modification_time,
									refresh_window->start,
									/* Refresh window not exclusive at end */
									MIN(refresh_window->end - 1,
										invalidation->greatest_modified_value));
			result = INVAL_CUT;
		}

		if (invalidation->lowest_modified_value < refresh_window->end &&
			invalidation->greatest_modified_value >= refresh_window->end)
		{
			/*
			 * Need to cut in left end:
			 *
			 * |------|
			 *    [++++++++]
			 *
			 *         [+++]
			 */
			upper = create_invalidation_tup(tupdesc,
											cagg_hyper_id,
											invalidation->modification_time,
											refresh_window->end,
											invalidation->greatest_modified_value,
											invalidation->frozen);
			set_remainder_after_cut(remainder,
									cagg_hyper_id,
									invalidation->modification_time,
									MAX(invalidation->lowest_modified_value, refresh_window->start),
									/* Refresh window exclusive at end */
									refresh_window->end - 1);
			result = INVAL_CUT;
		}
	}

	/* Insert any modifications into the cagg invalidation log */
	if (result == INVAL_CUT)
	{
		CatalogSecurityContext sec_ctx;
		HeapTuple other_range = NULL;

		ts_catalog_database_info_become_owner(ts_catalog_database_info_get(), &sec_ctx);

		/* We'd like to do one update (unless the TID is not set), and
		 * optionally one insert. We pick one of the tuples for an update, and
		 * the other one will be an insert. */
		if (lower || upper)
		{
			HeapTuple tup = lower ? lower : upper;
			other_range = lower ? upper : lower;

			/* If the TID is set, we are updating an existing tuple, i.e., we
			 * are processing and entry in the cagg log itself. Otherwise, we
			 * are processing the hypertable invalidation log and need to
			 * insert a new entry. */
			if (ItemPointerIsValid(&invalidation->tid))
			{
				ItemPointerData tid = invalidation->tid;
				ts_catalog_update_tid_only(state->cagg_log_rel, &tid, tup);
			}
			else
				ts_catalog_insert_only(state->cagg_log_rel, tup);

			heap_freetuple(tup);
		}

		if (other_range)
		{
			ts_catalog_insert_only(state->cagg_log_rel, other_range);
			heap_freetuple(other_range);
		}

		ts_catalog_restore_user(&sec_ctx);
	}

	return result;
}

/*
 * Macro to set an Invalidation from a tuple. The tuple can either have the
 * format of the hypertable invalidation log or the continuous aggregate
 * invalidation log (as determined by the type parameter).
 */
#define INVALIDATION_ENTRY_SET(entry, ti, hypertable_id, type)                                     \
	do                                                                                             \
	{                                                                                              \
		bool should_free;                                                                          \
		HeapTuple tuple = ts_scanner_fetch_heap_tuple(ti, false, &should_free);                    \
		type form;                                                                                 \
		form = (type) GETSTRUCT(tuple);                                                            \
		(entry)->hyper_id = form->hypertable_id;                                                   \
		(entry)->modification_time = form->modification_time;                                      \
		(entry)->lowest_modified_value = form->lowest_modified_value;                              \
		(entry)->greatest_modified_value = form->greatest_modified_value;                          \
		(entry)->is_modified = false;                                                              \
		ItemPointerCopy(&tuple->t_self, &(entry)->tid);                                            \
                                                                                                   \
		if (should_free)                                                                           \
			heap_freetuple(tuple);                                                                 \
	} while (0);

void
invalidation_entry_set_from_hyper_invalidation(Invalidation *entry, const TupleInfo *ti,
											   int32 hyper_id)
{
	bool should_free;
	HeapTuple tuple = ts_scanner_fetch_heap_tuple(ti, false, &should_free);
	Form_continuous_aggs_hypertable_invalidation_log form;

	form = (Form_continuous_aggs_hypertable_invalidation_log) GETSTRUCT(tuple);
	/* Since hypertable invalidations are moved to the continuous aggregate
	 * invalidation log, a different hypertable ID must be set (the ID of the
	 * materialized hypertable). */
	entry->hyper_id = hyper_id;
	entry->modification_time = form->modification_time;
	entry->lowest_modified_value = form->lowest_modified_value;
	entry->greatest_modified_value = form->greatest_modified_value;
	entry->is_modified = false;
	entry->frozen = false;
	ItemPointerCopy(&tuple->t_self, &(entry)->tid);

	if (should_free)
		heap_freetuple(tuple);
}

static void
invalidation_entry_set_from_cagg_invalidation(Invalidation *entry, const TupleInfo *ti)
{
	bool should_free;
	HeapTuple tuple = ts_scanner_fetch_heap_tuple(ti, false, &should_free);
	Form_continuous_aggs_materialization_invalidation_log form;
	form = (Form_continuous_aggs_materialization_invalidation_log) GETSTRUCT(tuple);

	entry->hyper_id = form->materialization_id;
	entry->modification_time = form->modification_time;
	entry->lowest_modified_value = form->lowest_modified_value;
	entry->greatest_modified_value = form->greatest_modified_value;
	entry->frozen = form->frozen;
	entry->is_modified = false;
	ItemPointerCopy(&tuple->t_self, &(entry)->tid);

	if (should_free)
		heap_freetuple(tuple);
}

/*
 * Try to merge two invalidations into one.
 *
 * Returns true if the invalidations were merged, otherwise false.
 *
 * Given that we scan ordered on lowest_modified_value, the previous and
 * current invalidation can overlap in two ways (generalized):
 *
 * |------|
 *    |++++++++|
 *
 * |-------------|
 *    |++++++++|
 *
 * The closest non-overlapping case is (note that adjacent invalidations can
 * be merged since they are inclusive in both ends):
 *
 * |--|
 *     |++++++++|
 *
 */
static bool
invalidation_entry_try_merge(Invalidation *entry, const Invalidation *newentry)
{
	if (!IS_VALID_INVALIDATION(newentry))
		return false;

	/* Should never merge frozen and unfrozen entries */
	Assert(entry->frozen == newentry->frozen);

	/* Quick exit if no overlap */
	if (!invalidations_can_be_merged(entry, newentry))
		return false;

	/* Check if the new entry expands beyond the old one (first case above) */
	if (entry->greatest_modified_value < newentry->greatest_modified_value)
	{
		entry->greatest_modified_value = newentry->greatest_modified_value;
		entry->is_modified = true;
	}

	return true;
}

static void
cut_and_insert_new_cagg_invalidation(const CaggInvalidationState *state,
									 const InternalTimeRange *refresh_window,
									 const Invalidation *entry, int32 cagg_hyper_id)
{
	CatalogSecurityContext sec_ctx;
	TupleDesc tupdesc = RelationGetDescr(state->cagg_log_rel);
	HeapTuple newtup;

	newtup = create_invalidation_tup(tupdesc,
									 cagg_hyper_id,
									 entry->modification_time,
									 entry->lowest_modified_value,
									 entry->greatest_modified_value,
									 entry->frozen);

	ts_catalog_database_info_become_owner(ts_catalog_database_info_get(), &sec_ctx);
	ts_catalog_insert_only(state->cagg_log_rel, newtup);
	ts_catalog_restore_user(&sec_ctx);
}

/*
 * Process invalidations in the hypertable invalidation log.
 *
 * Copy and delete all entries from the hypertable invalidation log. For the
 * continuous aggregate that is getting refreshed, we also match the
 * invalidation against the refresh window and perform additional processing
 * (cutting or deleting and merging); work that we'd otherwise have to do
 * later in the cagg invalidation log.
 *
 * Note that each entry gets one copy per continuous aggregate in the cagg
 * invalidation log (unless it was merged or matched the refresh
 * window). These copied entries are later used to track invalidations across
 * refreshes on a per-cagg basis.
 *
 * After this function has run, there are no entries left in the hypertable
 * invalidation log.
 */
static void
move_invalidations_from_hyper_to_cagg_log(const CaggInvalidationState *state,
										  const InternalTimeRange *refresh_window)
{
	int32 hyper_id = state->cagg.data.raw_hypertable_id;
	List *cagg_ids = get_cagg_ids(hyper_id);
	int32 last_cagg_hyper_id;
	ListCell *lc;

	Assert(list_length(cagg_ids) > 0);
	last_cagg_hyper_id = llast_int(cagg_ids);

	/* We use a per-tuple memory context in the scan loop since we could be
	 * processing a lot of invalidations (basically an unbounded
	 * amount). Initialize it here by resetting it. */
	MemoryContextReset(state->per_tuple_mctx);

	/*
	 * Looping over all continuous aggregates in the outer loop ensures all
	 * tuples for a specific continuous aggregate is inserted consecutively in
	 * the cagg invalidation log. This creates better locality for scanning
	 * the invalidations later.
	 */
	foreach (lc, cagg_ids)
	{
		int32 cagg_hyper_id = lfirst_int(lc);
		Invalidation mergedentry;
		ScanIterator iterator;

		invalidation_entry_reset(&mergedentry);
		hypertable_invalidation_scan_init(&iterator, hyper_id, RowExclusiveLock);
		iterator.ctx.snapshot = state->snapshot;

		/* Scan all invalidations */
		ts_scanner_foreach(&iterator)
		{
			TupleInfo *ti;
			MemoryContext oldmctx;
			Invalidation logentry;

			oldmctx = MemoryContextSwitchTo(state->per_tuple_mctx);
			ti = ts_scan_iterator_tuple_info(&iterator);

			invalidation_entry_set_from_hyper_invalidation(&logentry, ti, cagg_hyper_id);

			if (!IS_VALID_INVALIDATION(&mergedentry))
			{
				mergedentry = logentry;
				mergedentry.hyper_id = cagg_hyper_id;
			}
			else if (!invalidation_entry_try_merge(&mergedentry, &logentry))
			{
				cut_and_insert_new_cagg_invalidation(state,
													 refresh_window,
													 &mergedentry,
													 cagg_hyper_id);
				mergedentry = logentry;
			}

			if (cagg_hyper_id == last_cagg_hyper_id)
			{
				CatalogSecurityContext sec_ctx;

				/* The invalidation has been processed for all caggs, so the
				 * only thing left is to delete it from the source hypertable
				 * invalidation log. */
				ts_catalog_database_info_become_owner(ts_catalog_database_info_get(), &sec_ctx);
				ts_catalog_delete_tid_only(ti->scanrel, &logentry.tid);
				ts_catalog_restore_user(&sec_ctx);
			}

			MemoryContextSwitchTo(oldmctx);
			MemoryContextReset(state->per_tuple_mctx);
		}

		ts_scan_iterator_close(&iterator);

		/* Handle the last merged invalidation */
		if (IS_VALID_INVALIDATION(&mergedentry))
			cut_and_insert_new_cagg_invalidation(state,
												 refresh_window,
												 &mergedentry,
												 cagg_hyper_id);
	}
}

/*
 * Cut an invalidation and return the part, if any, that remains within the
 * refresh window.
 */
static Invalidation
cut_cagg_invalidation(const CaggInvalidationState *state, const InternalTimeRange *refresh_window,
					  const Invalidation *entry)
{
	InvalidationResult result;
	Invalidation remainder;
	ItemPointerData tid = entry->tid;

	invalidation_entry_reset(&remainder);

	result = cut_invalidation_along_refresh_window(state, entry, refresh_window, &remainder);

	switch (result)
	{
		case INVAL_NOMATCH:
			/* If no cutting was done (i.e., the invalidation was outside the
			 * refresh window), but the invalidation was previously merged
			 * (expanded) with another invalidation, then we still need to
			 * update it. */
			if (entry->is_modified)
			{
				HeapTuple tuple = create_invalidation_tup(RelationGetDescr(state->cagg_log_rel),
														  entry->hyper_id,
														  entry->modification_time,
														  entry->lowest_modified_value,
														  entry->greatest_modified_value,
														  entry->frozen);
				ts_catalog_update_tid_only(state->cagg_log_rel, &tid, tuple);
				heap_freetuple(tuple);
			}
			break;
		case INVAL_DELETE:
			ts_catalog_delete_tid_only(state->cagg_log_rel, &tid);
			break;
		case INVAL_CUT:
			/* Nothing to do */
			break;
	}

	return remainder;
}

static Invalidation
cut_cagg_invalidation_and_compute_remainder(const CaggInvalidationState *state,
											const InternalTimeRange *refresh_window,
											const Invalidation *mergedentry,
											const Invalidation *current_remainder)
{
	Invalidation new_remainder;
	Invalidation remainder = *current_remainder;

	/* The previous and current invalidation could not be merged. We
	 * need to cut the prev invalidation against the refresh window */
	new_remainder = cut_cagg_invalidation(state, refresh_window, mergedentry);

	if (!IS_VALID_INVALIDATION(&remainder))
		remainder = new_remainder;
	else if (!invalidation_entry_try_merge(&remainder, &new_remainder))
	{
		save_invalidation_for_refresh(state, &remainder);
		remainder = new_remainder;
	}

	return remainder;
}

static bool
invalidation_overlaps_window(const Invalidation *invalidation, const InternalTimeRange *window)
{
	return (invalidation->lowest_modified_value < window->end &&
			invalidation->greatest_modified_value >= window->start);
}

typedef enum CaggLogClearMode
{
	CLEAR_FOR_REFRESH,
	CLEAR_FOR_UNFREEZE,
} CaggLogClearMode;

/*
 * Clear all cagg invalidations that match a refresh window.
 *
 * This function clears all invalidations in the cagg invalidation log that
 * matches a window. Note that the refresh currently doesn't make use of the
 * invalidations to optimize the materialization.
 *
 * An invalidation entry that gets processed is either completely enclosed
 * (covered) by the refresh window, or it partially overlaps. In the former
 * case, the invalidation entry is removed and for the latter case it is
 * cut. Thus, an entry can either disappear, reduce in size, or be cut in two.
 *
 * Note that the refresh window is inclusive at the start and exclusive at the
 * end.
 */
static void
clear_cagg_invalidations(const CaggInvalidationState *state,
						 const InternalTimeRange *refresh_window, const CaggLogClearMode mode)
{
	ScanIterator iterator;
	int32 cagg_hyper_id = state->cagg.data.mat_hypertable_id;
	Invalidation mergedentry;
	Invalidation remainder;

	invalidation_entry_reset(&mergedentry);
	invalidation_entry_reset(&remainder);

	if (mode == CLEAR_FOR_UNFREEZE)
		cagg_invalidations_scan_by_hypertable_and_frozen_init(&iterator,
															  cagg_hyper_id,
															  refresh_window->end,
															  true,
															  RowExclusiveLock);
	else
		cagg_invalidations_scan_by_hypertable_init(&iterator, cagg_hyper_id, RowExclusiveLock);
	iterator.ctx.snapshot = state->snapshot;

	MemoryContextReset(state->per_tuple_mctx);

	/* Process all invalidations for the continuous aggregate */
	ts_scanner_foreach(&iterator)
	{
		TupleInfo *ti = ts_scan_iterator_tuple_info(&iterator);
		MemoryContext oldmctx;
		Invalidation logentry;

		oldmctx = MemoryContextSwitchTo(state->per_tuple_mctx);
		invalidation_entry_set_from_cagg_invalidation(&logentry, ti);

		if (mode == CLEAR_FOR_REFRESH && logentry.frozen)
		{
			if (invalidation_overlaps_window(&logentry, refresh_window))
				ereport(ERROR,
						(errcode(ERRCODE_TS_CONTINUOUS_AGGREGATE_FROZEN),
						 errmsg("continuous aggregate is frozen"),
						 errhint("Unfreeze the continuous aggregate to refresh.")));
		}
		else if (!IS_VALID_INVALIDATION(&mergedentry))
			mergedentry = logentry;
		else if (invalidation_entry_try_merge(&mergedentry, &logentry))
		{
			/*
			 * The previous and current invalidation were merged into
			 * one entry (i.e., they overlapped or were adjacent).
			 */
			ts_catalog_delete_tid_only(state->cagg_log_rel, &logentry.tid);
		}
		else
		{
			remainder = cut_cagg_invalidation_and_compute_remainder(state,
																	refresh_window,
																	&mergedentry,
																	&remainder);
			mergedentry = logentry;
		}

		MemoryContextSwitchTo(oldmctx);
		MemoryContextReset(state->per_tuple_mctx);
	}

	ts_scan_iterator_close(&iterator);

	/* Handle the last (merged) invalidation */
	if (IS_VALID_INVALIDATION(&mergedentry))
		remainder = cut_cagg_invalidation_and_compute_remainder(state,
																refresh_window,
																&mergedentry,
																&remainder);

	/* Handle the last (merged) remainder */
	save_invalidation_for_refresh(state, &remainder);
}

void
invalidation_process_hypertable_log(const ContinuousAgg *cagg,
									const InternalTimeRange *refresh_window)
{
	CaggInvalidationState state;

	invalidation_state_init(&state, cagg);
	move_invalidations_from_hyper_to_cagg_log(&state, refresh_window);
	invalidation_state_cleanup(&state);
}

InvalidationStore *
invalidation_process_cagg_log(const ContinuousAgg *cagg, const InternalTimeRange *refresh_window)
{
	CaggInvalidationState state;
	InvalidationStore *store = NULL;

	invalidation_state_init(&state, cagg);
	state.invalidations = tuplestore_begin_heap(false, false, work_mem);
	clear_cagg_invalidations(&state, refresh_window, CLEAR_FOR_REFRESH);

	if (tuplestore_tuple_count(state.invalidations) == 0)
	{
		tuplestore_end(state.invalidations);
	}
	else
	{
		store = palloc(sizeof(InvalidationStore));
		store->tupstore = state.invalidations;
		store->tupdesc = CreateTupleDescCopy(RelationGetDescr(state.cagg_log_rel));
	}

	invalidation_state_cleanup(&state);

	return store;
}

void
invalidation_cagg_log_unfreeze(const ContinuousAgg *cagg, const InternalTimeRange *unfreeze_window)
{
	CaggInvalidationState state;

	invalidation_state_init(&state, cagg);
	clear_cagg_invalidations(&state, unfreeze_window, CLEAR_FOR_UNFREEZE);
	invalidation_state_cleanup(&state);
}

void
invalidation_store_free(InvalidationStore *store)
{
	FreeTupleDesc(store->tupdesc);
	tuplestore_end(store->tupstore);
	pfree(store);
}
