/*
 * This file and its contents are licensed under the Timescale License.
 * Please see the included NOTICE for copyright information and
 * LICENSE-TIMESCALE for a copy of the license.
 */
#include <postgres.h>

#include <access/htup.h>
#include <access/htup_details.h>
#include <access/xact.h>
#include <executor/spi.h>
#include <extension.h>
#include <fmgr.h>
#include <funcapi.h>
#include <hypertable_cache.h>
#include <miscadmin.h>
#include <nodes/makefuncs.h>
#include <nodes/memnodes.h>
#include <parser/parse_func.h>
#include <scan_iterator.h>
#include <scanner.h>
#include <storage/lockdefs.h>
#include <time_bucket.h>
#include <time_utils.h>
#include <utils.h>
#include <utils/builtins.h>
#include <utils/elog.h>
#include <utils/lsyscache.h>
#include <utils/memutils.h>
#include <utils/palloc.h>
#include <utils/snapmgr.h>
#include <utils/tuplestore.h>

#include "cache.h"
#include "continuous_aggs/invalidation_threshold.h"
#include "continuous_aggs/materialize.h"
#include "debug_point.h"
#include "guc.h"
#include "invalidation.h"
#include "refresh.h"
#include "ts_catalog/catalog.h"
#include "ts_catalog/continuous_agg.h"
#include "ts_catalog/continuous_aggs_tenant_tracking.h"
#include "ts_catalog/continuous_aggs_watermark.h"

/*
 * Invalidation processing for continuous aggregates.
 *
 * Invalidations track the regions/intervals [start, end] of a continuous
 * aggregate that are out-of-date relative to the source hypertable on top of
 * which the aggregate is defined. When a continuous aggregate is out-of-date
 * across one or more regions, it can be refreshed with a window covering
 * those regions in order to bring it up-to-date with the source data again.
 *
 * Invalidations are generated by mutations on the source hypertable (INSERT,
 * DELETE, UPDATE, TRUNCATE, drop_chunks, etc.) and are initially written to a
 * hypertable invalidation log [hypertable_id, start, end].
 *
 * When a continuous aggregate is refreshed, invalidations are moved from the
 * hypertable invalidation log to a continuous aggregate invalidation log,
 * where each original entry creates one new entry per continuous aggregate
 * [cagg_id, start, end]. Thus, if one continuous aggregate is refreshed but
 * not others, then only the invalidations for the refreshed aggregate are
 * processed.
 *
 * Simplified, invalidations move through the following stages:
 *
 * insert_trigger => hypertable_inval_log => cagg_inval_log => refreshing
 *
 * Thus, invalidations are generated by mutations and are processed and used
 * as input for refreshing the a continuous aggregate.
 *
 * Invalidations can overlap or be duplicates. Therefore, invalidations are
 * merged during processing to reduce the number of entries in the logs. This
 * typically happens during a refresh of a continuous aggregate, which also
 * cuts invalidations along the refresh window. The cutting will leave some
 * parts of entries in the invalidation log while the entries that fall
 * within the refresh window are stored in an invalidation store and used for
 * refreshing:
 *
 *       |-------------|    refresh window
 *
 *   |-----|  |---| |----|  invalidations
 *
 *             =>
 *
 *   |---|             |--| invalidations that remain in the log
 *
 *       |-|  |---| |--|    invalidations that are used for refreshing
 *
 */

/*
 * Processing state used while processing the materialization invalidation log
 * and refreshing the continuous aggregate.
 */
typedef struct ContinuousAggInvalidationState
{
	const ContinuousAgg *cagg;
	MemoryContext per_tuple_mctx;
	Relation cagg_log_rel;
	Snapshot snapshot;
} ContinuousAggInvalidationState;

/*
 * Processing state used while moving invalidations from hypertable
 * invalidation log to materialization invalidation log.
 */
typedef struct HypertableInvalidationState
{
	int32 hypertable_id;
	Oid dimtype; /* Type of the underlying hypertable's bucketed attribute */
	const ContinuousAggInfo *all_caggs;
	MemoryContext per_tuple_mctx;
	Relation cagg_log_rel;
	Snapshot snapshot;
} HypertableInvalidationState;

typedef enum ContinuousAggTableType
{
	HYPER_INVALIDATION_LOG,
	CAGG_INVALIDATION_LOG,
} ContinuousAggTableType;

static Relation open_cagg_table(ContinuousAggTableType type, LOCKMODE lockmode);
static void hypertable_invalidation_scan_init(ScanIterator *iterator, int32 hyper_id,
											  LOCKMODE lockmode);
static bool insert_cagg_invalidation_entry(Relation cagg_log_rel, const Invalidation *invalidation);
static bool write_cagg_invalidation_entry(Relation cagg_log_rel, const Invalidation *invalidation,
										  ItemPointer update_tid);
static void invalidation_entry_set(Invalidation *inner_range, int32 hyper_id,
								   int64 lowest_modified_value, int64 greatest_modified_value,
								   int32 seqnum);
static void invalidation_entry_reset(Invalidation *entry);
static void
invalidation_entry_set_from_hyper_invalidation(Invalidation *entry, const TupleInfo *ti,
											   int32 hyper_id, Oid dimtype,
											   const ContinuousAggBucketFunction *bucket_function);
static void
invalidation_entry_set_from_cagg_invalidation(Invalidation *entry, const TupleInfo *ti, Oid dimtype,
											  const ContinuousAggBucketFunction *bucket_function);
static bool invalidations_can_be_merged(const Invalidation *a, const Invalidation *b,
										bool seqnum_aware);
static bool invalidation_entry_try_merge(Invalidation *entry, const Invalidation *newentry,
										 bool seqnum_aware);
static void move_invalidations_from_hyper_to_cagg_log(const HypertableInvalidationState *state);
static void cagg_invalidations_scan_by_hypertable_init(ScanIterator *iterator, int32 cagg_hyper_id,
													   LOCKMODE lockmode, int64 window_end);
static ScanFilterResult cagg_invalidation_window_end_filter(const TupleInfo *ti, void *data);
static Invalidation cut_cagg_invalidation(const ContinuousAggInvalidationState *state,
										  const InternalTimeRange *refresh_window,
										  const Invalidation *entry);
static Invalidation cut_cagg_invalidation_and_compute_inner_range(
	const ContinuousAggInvalidationState *state, const InternalTimeRange *refresh_window,
	const Invalidation *mergedentry, const Invalidation *current_inner_range);
static void process_cagg_invalidations_for_refresh(const ContinuousAggInvalidationState *state,
												   const InternalTimeRange *refresh_window);
static void cagg_invalidation_state_init(ContinuousAggInvalidationState *state,
										 const ContinuousAgg *cagg);
static void cagg_invalidation_state_cleanup(const ContinuousAggInvalidationState *state);

static Relation
open_cagg_table(ContinuousAggTableType type, LOCKMODE lockmode)
{
	static const CatalogTable logmappings[] = {
		[HYPER_INVALIDATION_LOG] = CONTINUOUS_AGGS_HYPERTABLE_INVALIDATION_LOG,
		[CAGG_INVALIDATION_LOG] = CONTINUOUS_AGGS_MATERIALIZATION_INVALIDATION_LOG,
	};
	Catalog *catalog = ts_catalog_get();
	Oid relid = catalog_get_table_id(catalog, logmappings[type]);

	return table_open(relid, lockmode);
}

static void
hypertable_invalidation_scan_init(ScanIterator *iterator, int32 hyper_id, LOCKMODE lockmode)
{
	*iterator = ts_scan_iterator_create(CONTINUOUS_AGGS_HYPERTABLE_INVALIDATION_LOG,
										lockmode,
										CurrentMemoryContext);
	iterator->ctx.index = catalog_get_index(ts_catalog_get(),
											CONTINUOUS_AGGS_HYPERTABLE_INVALIDATION_LOG,
											CONTINUOUS_AGGS_HYPERTABLE_INVALIDATION_LOG_IDX);
	ts_scan_iterator_scan_key_init(
		iterator,
		Anum_continuous_aggs_hypertable_invalidation_log_idx_hypertable_id,
		BTEqualStrategyNumber,
		F_INT4EQ,
		Int32GetDatum(hyper_id));
}

HeapTuple
create_cagg_invalidation_tup(const TupleDesc tupdesc, int32 cagg_hyper_id, int64 start, int64 end,
							 int32 seqnum)
{
	Datum values[Natts_continuous_aggs_materialization_invalidation_log] = { 0 };
	bool isnull[Natts_continuous_aggs_materialization_invalidation_log] = { false };

	values[AttrNumberGetAttrOffset(
		Anum_continuous_aggs_materialization_invalidation_log_materialization_id)] =
		Int32GetDatum(cagg_hyper_id);
	values[AttrNumberGetAttrOffset(
		Anum_continuous_aggs_materialization_invalidation_log_lowest_modified_value)] =
		Int64GetDatum(start);
	values[AttrNumberGetAttrOffset(
		Anum_continuous_aggs_materialization_invalidation_log_greatest_modified_value)] =
		Int64GetDatum(end);
	/* seqnum 0 means "no associated granular tracking" and is stored as SQL NULL. */
	if (seqnum == 0)
	{
		isnull[AttrNumberGetAttrOffset(
			Anum_continuous_aggs_materialization_invalidation_log_seqnum)] = true;
	}
	else
	{
		values[AttrNumberGetAttrOffset(
			Anum_continuous_aggs_materialization_invalidation_log_seqnum)] = Int32GetDatum(seqnum);
	}

	return heap_form_tuple(tupdesc, values, isnull);
}

/*
 * Add an entry to the continuous aggregate invalidation log.
 * This is called to manually invalidate a whole range of data for continuous aggregates,
 * bypassing DMLs (and hypertable_invalidation_log). Therefore the invalidation does not
 * have an associated granular tracking.
 */
void
invalidation_cagg_log_add_entry(int32 cagg_hyper_id, int64 start, int64 end)
{
	Relation rel = open_cagg_table(CAGG_INVALIDATION_LOG, RowExclusiveLock);
	Invalidation invalidation;

	Assert(start <= end);
	/* Manual cagg invalidation has no associated granular tracking, so seqnum 0
	 * (stored as NULL). */
	invalidation_entry_set(&invalidation, cagg_hyper_id, start, end, 0);
	insert_cagg_invalidation_entry(rel, &invalidation);
	table_close(rel, NoLock);
}

void
invalidation_hyper_log_add_entry(int32 hyper_id, int64 start, int64 end, int32 seqnum)
{
	Relation rel = open_cagg_table(HYPER_INVALIDATION_LOG, RowExclusiveLock);
	CatalogSecurityContext sec_ctx;
	Datum values[Natts_continuous_aggs_hypertable_invalidation_log];
	bool nulls[Natts_continuous_aggs_hypertable_invalidation_log] = { false };

	Assert(start <= end);
	values[AttrNumberGetAttrOffset(
		Anum_continuous_aggs_hypertable_invalidation_log_hypertable_id)] = Int32GetDatum(hyper_id);
	values[AttrNumberGetAttrOffset(
		Anum_continuous_aggs_hypertable_invalidation_log_lowest_modified_value)] =
		Int64GetDatum(start);
	values[AttrNumberGetAttrOffset(
		Anum_continuous_aggs_hypertable_invalidation_log_greatest_modified_value)] =
		Int64GetDatum(end);
	/* seqnum 0 means untracked and is stored as SQL NULL. */
	if (seqnum == 0)
	{
		nulls[AttrNumberGetAttrOffset(Anum_continuous_aggs_hypertable_invalidation_log_seqnum)] =
			true;
	}
	else
	{
		values[AttrNumberGetAttrOffset(Anum_continuous_aggs_hypertable_invalidation_log_seqnum)] =
			Int32GetDatum(seqnum);
	}

	ts_catalog_database_info_become_owner(ts_catalog_database_info_get(), &sec_ctx);
	ts_catalog_insert_values(rel, RelationGetDescr(rel), values, nulls);
	ts_catalog_restore_user(&sec_ctx);
	table_close(rel, NoLock);
	elog(DEBUG1,
		 "hypertable log for hypertable %d added entry [" INT64_FORMAT ", " INT64_FORMAT "]",
		 hyper_id,
		 start,
		 end);
}

/*
 * Invalidate one or more continuous aggregates.
 *
 * Add an invalidation in the given range. The invalidation is added either to
 * the hypertable invalidation log or the continuous aggregate invalidation
 * log depending on the type of the given hypertable. If the hypertable is a
 * "raw" hypertable (i.e., one that has one or more continuous aggregates), the
 * entry is added to the hypertable invalidation log and will invalidate all
 * the associated continuous aggregates. If the hypertable is instead an
 * materialized hypertable, the entry is added to the cagg invalidation log
 * and only invalidates the continuous aggregate owning that materialized
 * hypertable.
 */
void
continuous_agg_invalidate_raw_ht(const Hypertable *raw_ht, int64 start, int64 end)
{
	Assert(raw_ht != NULL);

	/* TODO: stamp the proper per-hypertable tenant-tracking seqnum once the
	 * tracker flush is wired up; 0 means untracked (stored as NULL). */
	invalidation_hyper_log_add_entry(raw_ht->fd.id, start, end, 0);
}

void
continuous_agg_invalidate_mat_ht(const Hypertable *raw_ht, const Hypertable *mat_ht, int64 start,
								 int64 end)
{
	Assert((raw_ht != NULL) && (mat_ht != NULL));

	invalidation_cagg_log_add_entry(mat_ht->fd.id, start, end);
}

typedef enum InvalidationResult
{
	INVAL_NOMATCH,
	INVAL_FULLY_MATCH,
	INVAL_CUT,
} InvalidationResult;

static inline bool
IsValidInvalidation(const Invalidation *invalidation)
{
	Assert(invalidation->lowest_modified_value <= invalidation->greatest_modified_value);
	return invalidation->hyper_id != INVALID_HYPERTABLE_ID &&
		   invalidation->lowest_modified_value <= invalidation->greatest_modified_value;
}

static bool
write_cagg_invalidation_entry(Relation cagg_log_rel, const Invalidation *invalidation,
							  ItemPointer update_tid)
{
	CatalogSecurityContext sec_ctx;
	HeapTuple tup;

	if (!IsValidInvalidation(invalidation))
	{
		return false;
	}

	tup = create_cagg_invalidation_tup(RelationGetDescr(cagg_log_rel),
									   invalidation->hyper_id,
									   invalidation->lowest_modified_value,
									   invalidation->greatest_modified_value,
									   invalidation->seqnum);
	ts_catalog_database_info_become_owner(ts_catalog_database_info_get(), &sec_ctx);
	if (ItemPointerIsValid(update_tid))
	{
		ts_catalog_update_tid_only(cagg_log_rel, update_tid, tup);
	}
	else
	{
		ts_catalog_insert_only(cagg_log_rel, tup);
	}
	ts_catalog_restore_user(&sec_ctx);
	heap_freetuple(tup);

	return true;
}

static bool
insert_cagg_invalidation_entry(Relation cagg_log_rel, const Invalidation *invalidation)
{
	return write_cagg_invalidation_entry(cagg_log_rel, invalidation, NULL);
}

static void
invalidation_entry_set(Invalidation *inner_range, int32 hyper_id, int64 lowest_modified_value,
					   int64 greatest_modified_value, int32 seqnum)
{
	MemSet(inner_range, 0, sizeof(*inner_range));
	inner_range->hyper_id = hyper_id;
	inner_range->lowest_modified_value = lowest_modified_value;
	inner_range->greatest_modified_value = greatest_modified_value;
	inner_range->seqnum = seqnum;
}

/*
 * Try to cut an invalidation against the refresh window.
 *
 * If an invalidation entry overlaps with the refresh window, it needs
 * additional processing: it is either cut, deleted, or left unmodified.
 *
 * The part(s) of the invalidation that are outside the refresh window after
 * the cut will remain in the log. The part of the invalidation that fits
 * within the window is returned as the "inner range".
 *
 * Note that the refresh window is exclusive in the end while invalidations
 * are inclusive.
 */
static InvalidationResult
cut_invalidation_along_refresh_window(const ContinuousAggInvalidationState *state,
									  const Invalidation *invalidation,
									  const InternalTimeRange *refresh_window,
									  Invalidation *inner_range)
{
	int32 cagg_hyper_id = state->cagg->data.mat_hypertable_id;
	InvalidationResult result = INVAL_NOMATCH;
	Invalidation lower_range = { 0 };
	Invalidation upper_range = { 0 };

	Assert(inner_range != NULL);

	/* Entry is completely enclosed by the refresh window */
	if (invalidation->lowest_modified_value >= refresh_window->start &&
		invalidation->greatest_modified_value < refresh_window->end)
	{
		/*
		 * Entry completely enclosed — left in the log for Txn 3 to process:
		 *
		 * [---------------)
		 *     [+++++]
		 */

		result = INVAL_FULLY_MATCH;
	}
	else
	{
		if (invalidation->lowest_modified_value < refresh_window->start &&
			invalidation->greatest_modified_value >= refresh_window->start)
		{
			/*
			 * Need to cut in right end:
			 *
			 *     [------)
			 * [++++++]
			 *
			 * [++]
			 */
			invalidation_entry_set(&lower_range,
								   cagg_hyper_id,
								   invalidation->lowest_modified_value,
								   refresh_window->start - 1,
								   invalidation->seqnum);
			invalidation_entry_set(inner_range,
								   cagg_hyper_id,
								   refresh_window->start,
								   /* Refresh window not exclusive at end */
								   MIN(refresh_window->end - 1,
									   invalidation->greatest_modified_value),
								   invalidation->seqnum);
			result = INVAL_CUT;
		}

		if (invalidation->lowest_modified_value < refresh_window->end &&
			invalidation->greatest_modified_value >= refresh_window->end)
		{
			/*
			 * If the invalidation is already cut on the left above, the inner_range is set and
			 * will be reset here. The assert prevents from losing information from the inner_range.
			 */
			Assert((result == INVAL_CUT &&
					inner_range->lowest_modified_value == refresh_window->start) ||
				   result == INVAL_NOMATCH);

			/*
			 * Need to cut in left end:
			 *
			 * [------)
			 *    [++++++++]
			 *
			 *        [++++]
			 */
			invalidation_entry_set(&upper_range,
								   cagg_hyper_id,
								   refresh_window->end,
								   invalidation->greatest_modified_value,
								   invalidation->seqnum);
			invalidation_entry_set(inner_range,
								   cagg_hyper_id,
								   MAX(invalidation->lowest_modified_value, refresh_window->start),
								   /* Refresh window exclusive at end */
								   refresh_window->end - 1,
								   invalidation->seqnum);
			result = INVAL_CUT;
		}
	}

	/* Write outside parts back to the cagg invalidation log */
	if (result == INVAL_CUT)
	{
		/*
		 * We reuse (update) the original tuple slot for the first outside piece.
		 * If no TID is available (entry came from hyper log), insert instead.
		 * Any second outside piece is always a fresh insert.
		 */
		ItemPointerData tid = invalidation->tid;

		if (IsValidInvalidation(&lower_range))
		{
			write_cagg_invalidation_entry(state->cagg_log_rel,
										  &lower_range,
										  ItemPointerIsValid(&tid) ? &tid : NULL);
			ItemPointerSetInvalid(&tid); /* TID consumed — upper must be a fresh insert */
		}

		if (IsValidInvalidation(&upper_range))
		{
			write_cagg_invalidation_entry(state->cagg_log_rel,
										  &upper_range,
										  ItemPointerIsValid(&tid) ? &tid : NULL);
		}
	}

	return result;
}

static void
invalidation_entry_reset(Invalidation *entry)
{
	MemSet(entry, 0, sizeof(Invalidation));
}

/*
 * Expand an invalidation to bucket boundaries.
 *
 * Since a refresh always materializes full buckets, we can safely expand an
 * invalidation to bucket boundaries and in the process merge a lot more
 * invalidations.
 */
void
invalidation_expand_to_bucket_boundaries(Invalidation *inv, Oid time_type_oid,
										 const ContinuousAggBucketFunction *bucket_function)
{
	const int64 time_dimension_min = ts_time_get_min(time_type_oid);
	const int64 time_dimension_max = ts_time_get_max(time_type_oid);
	int64 min_bucket_start;
	int64 max_bucket_end;

	if (bucket_function->bucket_fixed_interval == false)
	{
		ts_compute_circumscribed_bucketed_refresh_window_variable(&inv->lowest_modified_value,
																  &inv->greatest_modified_value,
																  bucket_function);
		/* ts_compute_circumscribed_bucketed_refresh_window_variable returns the start of the
		 * next bucket as the end (exclusive). Since invalidations are inclusive at both ends,
		 * subtract 1 to get the last value of the current bucket (inclusive).
		 * Don't adjust infinity values. */
		if (inv->greatest_modified_value != INVAL_POS_INFINITY &&
			inv->greatest_modified_value != INVAL_NEG_INFINITY)
		{
			inv->greatest_modified_value = int64_saturating_sub(inv->greatest_modified_value, 1);
		}
		return;
	}

	int64 bucket_width = ts_continuous_agg_fixed_bucket_width(bucket_function);
	Assert(bucket_width > 0);

	/* Compute the start of the "first" bucket for the type. The min value
	 * must be at the start of the "first" bucket or somewhere in the
	 * bucket. If the min value falls on the exact start of the bucket we are
	 * good. Otherwise, we need to move to the next full bucket. */
	min_bucket_start = ts_time_saturating_add(time_dimension_min, bucket_width - 1, time_type_oid);
	min_bucket_start = ts_time_bucket_by_type(bucket_width, min_bucket_start, time_type_oid);

	/* Compute the end of the "last" bucket for the time type. Remember that
	 * invalidations are inclusive, so the "greatest" value should be the last
	 * value of the last full bucket. Either the max value is already the last
	 * value of the last bucket, or we need to return the last value of the
	 * previous full bucket.  */
	max_bucket_end = ts_time_bucket_by_type(bucket_width, time_dimension_max, time_type_oid);

	/* Check if the max value was already the last value of the last bucket */
	if (ts_time_saturating_add(max_bucket_end, bucket_width - 1, time_type_oid) ==
		time_dimension_max)
	{
		max_bucket_end = time_dimension_max;
	}
	else
	{
		/* The last bucket was partial. To get the end of previous bucket, we
		 * need to move one step down from the partial last bucket. */
		max_bucket_end = ts_time_saturating_sub(max_bucket_end, 1, time_type_oid);
	}

	if (inv->lowest_modified_value < min_bucket_start)
	{
		/* Below the min bucket, so treat as invalid to -infinity. */
		inv->lowest_modified_value = INVAL_NEG_INFINITY;
	}
	else if (inv->lowest_modified_value > max_bucket_end)
	{
		/* Above the max bucket, so treat as invalid to +infinity. */
		inv->lowest_modified_value = INVAL_POS_INFINITY;
	}
	else
	{
		inv->lowest_modified_value = cagg_fixed_current_bucket_start(inv->lowest_modified_value,
																	 time_type_oid,
																	 bucket_function);
	}

	if (inv->greatest_modified_value < min_bucket_start)
	{
		/* Below the min bucket, so treat as invalid to -infinity. */
		inv->greatest_modified_value = INVAL_NEG_INFINITY;
	}
	else if (inv->greatest_modified_value > max_bucket_end)
	{
		/* Above the max bucket, so treat as invalid to +infinity. */
		inv->greatest_modified_value = INVAL_POS_INFINITY;
	}
	else
	{
		inv->greatest_modified_value = cagg_fixed_current_bucket_start(inv->greatest_modified_value,
																	   time_type_oid,
																	   bucket_function);
		inv->greatest_modified_value =
			ts_time_saturating_add(inv->greatest_modified_value, bucket_width - 1, time_type_oid);
	}
}

/*
 * Set an Invalidation from a tuple of either the hypertable invalidation log or
 * the continuous aggregate invalidation log.
 *
 * Both logs share the same physical column layout -- (id, lowest_modified_value,
 * greatest_modified_value, seqnum) -- so the same attribute offsets apply to
 * both; we use the hypertable-log Anums here for both. The tuple is read with
 * heap_deform_tuple() rather than GETSTRUCT() because seqnum is nullable. seqnum
 * is mapped to 0 (untracked) when SQL NULL.
 */
static void
invalidation_entry_set_from_tuple(Invalidation *entry, const TupleInfo *ti)
{
	bool should_free;
	HeapTuple tuple = ts_scanner_fetch_heap_tuple(ti, false, &should_free);
	Datum values[Natts_continuous_aggs_hypertable_invalidation_log];
	bool nulls[Natts_continuous_aggs_hypertable_invalidation_log] = { false };

	heap_deform_tuple(tuple, ts_scanner_get_tupledesc(ti), values, nulls);

	entry->hyper_id = DatumGetInt32(values[AttrNumberGetAttrOffset(
		Anum_continuous_aggs_hypertable_invalidation_log_hypertable_id)]);
	entry->lowest_modified_value = DatumGetInt64(values[AttrNumberGetAttrOffset(
		Anum_continuous_aggs_hypertable_invalidation_log_lowest_modified_value)]);
	entry->greatest_modified_value = DatumGetInt64(values[AttrNumberGetAttrOffset(
		Anum_continuous_aggs_hypertable_invalidation_log_greatest_modified_value)]);
	/* seqnum is nullable: SQL NULL means untracked, mapped to 0. */
	if (nulls[AttrNumberGetAttrOffset(Anum_continuous_aggs_hypertable_invalidation_log_seqnum)])
	{
		entry->seqnum = 0;
	}
	else
	{
		entry->seqnum = DatumGetInt32(values[AttrNumberGetAttrOffset(
			Anum_continuous_aggs_hypertable_invalidation_log_seqnum)]);
	}
	entry->is_modified = false;
	ItemPointerCopy(&tuple->t_self, &entry->tid);

	if (should_free)
	{
		heap_freetuple(tuple);
	}
}

static void
invalidation_entry_set_from_hyper_invalidation(Invalidation *entry, const TupleInfo *ti,
											   int32 hyper_id, Oid dimtype,
											   const ContinuousAggBucketFunction *bucket_function)
{
	invalidation_entry_set_from_tuple(entry, ti);
	/* Since hypertable invalidations are moved to the continuous aggregate
	 * invalidation log, a different hypertable ID must be set (the ID of the
	 * materialized hypertable). */
	entry->hyper_id = hyper_id;
	invalidation_expand_to_bucket_boundaries(entry, dimtype, bucket_function);
}

static void
invalidation_entry_set_from_cagg_invalidation(Invalidation *entry, const TupleInfo *ti, Oid dimtype,
											  const ContinuousAggBucketFunction *bucket_function)
{
	invalidation_entry_set_from_tuple(entry, ti);

	/* It isn't strictly necessary to expand the invalidation to bucket
	 * boundaries here since all invalidations were already expanded when
	 * copied from the hypertable invalidation log. However, since
	 * invalidation expansion wasn't implemented in early 2.0.x versions of
	 * the extension, there might be unexpanded entries in the cagg
	 * invalidation log for some users. Therefore we try to expand
	 * invalidation entries also here, although in most cases it would do
	 * nothing. */
	invalidation_expand_to_bucket_boundaries(entry, dimtype, bucket_function);
}

/*
 * Check if two invalidations can be merged into one.
 *
 * Since invalidations are inclusive in both ends, two adjacent invalidations
 * can be merged.
 */
static bool
invalidations_can_be_merged(const Invalidation *a, const Invalidation *b, bool seqnum_aware)
{
	/*
	 * Only merge invalidations carrying the same granular-tracking seqnum, so a
	 * merged entry still maps to a single tenant-tracking seqnum. (seqnum 0 means
	 * "no associated trackings")
	 *
	 * Non-tracking caggs have their entries stamped seqnum 0 on the hyper->mat move,
	 * so this check is currently redundant for them -- but keep it explicit while cases
	 * like disabling granular refresh on a cagg that still has tracked entries are
	 * being worked out.  It can be removed once those are settled.
	 */
	if (seqnum_aware && a->seqnum != b->seqnum)
	{
		return false;
	}

	/* To account for adjacency, expand one window 1 step in each
	 * direction. This makes adjacent invalidations overlapping. */
	int64 a_start = int64_saturating_sub(a->lowest_modified_value, 1);
	int64 a_end = int64_saturating_add(a->greatest_modified_value, 1);

	return a_end >= b->lowest_modified_value && a_start <= b->greatest_modified_value;
}

/*
 * Try to merge two invalidations into one.
 *
 * Returns true if the invalidations were merged, otherwise false.
 *
 * Given that we scan ordered on lowest_modified_value, the previous and
 * current invalidation can overlap in two ways (generalized):
 *
 * |------|
 *    |++++++++|
 *
 * |-------------|
 *    |++++++++|
 *
 * The closest non-overlapping case is (note that adjacent invalidations can
 * be merged since they are inclusive in both ends):
 *
 * |--|
 *     |++++++++|
 *
 */
static bool
invalidation_entry_try_merge(Invalidation *entry, const Invalidation *newentry, bool seqnum_aware)
{
	if (!IsValidInvalidation(newentry))
	{
		return false;
	}

	/* Quick exit if no overlap */
	if (!invalidations_can_be_merged(entry, newentry, seqnum_aware))
	{
		return false;
	}

	/* Check if the new entry expands beyond the old one (first case above) */
	if (entry->greatest_modified_value < newentry->greatest_modified_value)
	{
		entry->greatest_modified_value = newentry->greatest_modified_value;
		entry->is_modified = true;
	}

	return true;
}

/*
 * Process invalidations in the hypertable invalidation log.
 *
 * Copy and delete all entries from the hypertable invalidation log.
 *
 * Note that each entry gets one copy per continuous aggregate in the cagg
 * invalidation log (unless it was merged or matched the refresh
 * window). These copied entries are later used to track invalidations across
 * refreshes on a per-cagg basis.
 *
 * After this function has run, there are no entries left in the hypertable
 * invalidation log.
 */
static void
move_invalidations_from_hyper_to_cagg_log(const HypertableInvalidationState *state)
{
	const ContinuousAggInfo *all_caggs = state->all_caggs;
	int32 hyper_id = state->hypertable_id;
	int32 last_cagg_hyper_id;
	ListCell *lc1, *lc2, *lc3;

	last_cagg_hyper_id = llast_int(all_caggs->mat_hypertable_ids);

	/* We use a per-tuple memory context in the scan loop since we could be
	 * processing a lot of invalidations (basically an unbounded
	 * amount). Initialize it here by resetting it. */
	MemoryContextReset(state->per_tuple_mctx);

	/*
	 * Looping over all continuous aggregates in the outer loop ensures all
	 * tuples for a specific continuous aggregate is inserted consecutively in
	 * the cagg invalidation log. This creates better locality for scanning
	 * the invalidations later.
	 */
	forthree (lc1,
			  all_caggs->mat_hypertable_ids,
			  lc2,
			  all_caggs->bucket_functions,
			  lc3,
			  all_caggs->granular_refresh_enabled)
	{
		int32 cagg_hyper_id = lfirst_int(lc1);
		const ContinuousAggBucketFunction *bucket_function = lfirst(lc2);
		bool granular_refresh_enabled = lfirst_int(lc3);

		Invalidation mergedentry;
		ScanIterator iterator;

		invalidation_entry_reset(&mergedentry);
		hypertable_invalidation_scan_init(&iterator, hyper_id, RowExclusiveLock);
		iterator.ctx.snapshot = state->snapshot;

		/* Scan all invalidations */
		ts_scanner_foreach(&iterator)
		{
			TupleInfo *ti;
			MemoryContext oldmctx;
			Invalidation logentry;

			oldmctx = MemoryContextSwitchTo(state->per_tuple_mctx);
			ti = ts_scan_iterator_tuple_info(&iterator);

			invalidation_entry_set_from_hyper_invalidation(&logentry,
														   ti,
														   cagg_hyper_id,
														   state->dimtype,
														   bucket_function);

			/* A cagg that does not do granular refresh carries no granular
			 * seqnum: stamp its copies untracked (0) so its mat log never gates
			 * on a seqnum. */
			if (!granular_refresh_enabled)
			{
				logentry.seqnum = 0;
			}

			if (!IsValidInvalidation(&mergedentry))
			{
				mergedentry = logentry;
				mergedentry.hyper_id = cagg_hyper_id;
			}
			else if (!invalidation_entry_try_merge(&mergedentry,
												   &logentry,
												   granular_refresh_enabled))
			{
				insert_cagg_invalidation_entry(state->cagg_log_rel, &mergedentry);
				mergedentry = logentry;
			}

			if (cagg_hyper_id == last_cagg_hyper_id)
			{
				CatalogSecurityContext sec_ctx;

				/* The invalidation has been processed for all caggs, so the
				 * only thing left is to delete it from the source hypertable
				 * invalidation log. */
				ts_catalog_database_info_become_owner(ts_catalog_database_info_get(), &sec_ctx);
				ts_catalog_delete_tid_only(ti->scanrel, &logentry.tid);
				ts_catalog_restore_user(&sec_ctx);
			}

			MemoryContextSwitchTo(oldmctx);
			MemoryContextReset(state->per_tuple_mctx);
		}

		ts_scan_iterator_close(&iterator);

		/* Handle the last merged invalidation */
		if (IsValidInvalidation(&mergedentry))
		{
			insert_cagg_invalidation_entry(state->cagg_log_rel, &mergedentry);
		}
	}
}

static void
cagg_invalidations_scan_by_hypertable_init(ScanIterator *iterator, int32 cagg_hyper_id,
										   LOCKMODE lockmode, int64 window_end)
{
	*iterator = ts_scan_iterator_create(CONTINUOUS_AGGS_MATERIALIZATION_INVALIDATION_LOG,
										lockmode,
										CurrentMemoryContext);
	iterator->ctx.index = catalog_get_index(ts_catalog_get(),
											CONTINUOUS_AGGS_MATERIALIZATION_INVALIDATION_LOG,
											CONTINUOUS_AGGS_MATERIALIZATION_INVALIDATION_LOG_IDX);
	ts_scan_iterator_scan_key_init(
		iterator,
		Anum_continuous_aggs_materialization_invalidation_log_idx_materialization_id,
		BTEqualStrategyNumber,
		F_INT4EQ,
		Int32GetDatum(cagg_hyper_id));
	ts_scan_iterator_scan_key_init(
		iterator,
		Anum_continuous_aggs_materialization_invalidation_log_idx_lowest_modified_value,
		BTLessStrategyNumber,
		F_INT8LT,
		Int64GetDatum(window_end));
}

/*
 * Cut an invalidation and return the part, if any, that remains within the
 * refresh window.
 */
static Invalidation
cut_cagg_invalidation(const ContinuousAggInvalidationState *state,
					  const InternalTimeRange *refresh_window, const Invalidation *entry)
{
	InvalidationResult result;
	Invalidation inner_range;
	ItemPointerData tid = entry->tid;

	invalidation_entry_reset(&inner_range);

	result = cut_invalidation_along_refresh_window(state, entry, refresh_window, &inner_range);

	switch (result)
	{
		case INVAL_NOMATCH:
			/* Entries completely outside the refresh window are skipped before
			 * reaching this function, so NOMATCH should never occur here. */
			Assert("NOMATCH should never occur here" == 0);
			break;
		case INVAL_FULLY_MATCH:
			/* Entry is left in the log for Txn 3. If it was merged with an adjacent
			 * entry, update it to reflect the expanded range. */
			if (entry->is_modified)
			{
				write_cagg_invalidation_entry(state->cagg_log_rel, entry, &tid);
			}
			break;
		case INVAL_CUT:
			/* Nothing to do, because the cuts have been written back to the invalidation log
			 * and the last merged inner range will be written at the end of
			 * process_cagg_invalidations_for_refresh*/
			break;
	}

	return inner_range;
}

static Invalidation
cut_cagg_invalidation_and_compute_inner_range(const ContinuousAggInvalidationState *state,
											  const InternalTimeRange *refresh_window,
											  const Invalidation *mergedentry,
											  const Invalidation *current_inner_range)
{
	Invalidation new_inner_range;
	Invalidation inner_range = *current_inner_range;

	/* The previous and current invalidation could not be merged. We
	 * need to cut the prev invalidation against the refresh window */
	new_inner_range = cut_cagg_invalidation(state, refresh_window, mergedentry);

	if (!IsValidInvalidation(&inner_range))
	{
		inner_range = new_inner_range;
	}
	else if (IsValidInvalidation(&new_inner_range) &&
			 !invalidation_entry_try_merge(&inner_range,
										   &new_inner_range,
										   state->cagg->data.granular_refresh_enabled))
	{
		insert_cagg_invalidation_entry(state->cagg_log_rel, &inner_range);
		inner_range = new_inner_range;
	}

	return inner_range;
}

/*
 * Process cagg invalidation log entries against a refresh window (Txn 2).
 *
 * Scans the cagg invalidation log for entries that overlap the refresh window
 * and splits them so that the parts inside and outside the window become
 * separate log entries. Entries completely before the window are skipped.
 *
 * For each overlapping entry:
 *   - INVAL_FULLY_MATCH: entry is completely enclosed by the window and left
 *     in the log as-is for Txn 3 to materialize (updated if it was merged
 *     with an adjacent entry).
 *   - INVAL_CUT: entry partially overlaps the window and is split. The outside
 *     part(s) are written back to the log; the inside part is inserted as a
 *     new log entry for Txn 3.
 *
 * Because the refresh window has been inscribed to bucket boundaries by the
 * caller, all resulting inside and outside parts written back to the log are
 * guaranteed to start and end on bucket boundaries.
 *
 * Note that the refresh window is inclusive at the start and exclusive at the
 * end. This function assumes that invalidations are scanned in order of
 * lowest_modified_value.
 */
static void
process_cagg_invalidations_for_refresh(const ContinuousAggInvalidationState *state,
									   const InternalTimeRange *refresh_window)
{
	ScanIterator iterator;
	Invalidation mergedentry;
	Invalidation inner_range;

	invalidation_entry_reset(&mergedentry);
	invalidation_entry_reset(&inner_range);

	cagg_invalidations_scan_by_hypertable_init(&iterator,
											   state->cagg->data.mat_hypertable_id,
											   RowExclusiveLock,
											   refresh_window->end);
	iterator.ctx.data = (void *) &state;
	iterator.ctx.snapshot = state->snapshot;
	ScanTupLock scantuplock = {
		.waitpolicy = LockWaitSkip,
		.lockmode = LockTupleExclusive,
		.lockflags = TUPLE_LOCK_FLAG_FIND_LAST_VERSION,
	};
	iterator.ctx.tuplock = &scantuplock;
	iterator.ctx.flags = SCANNER_F_KEEPLOCK;

	/*
	 * Concurrent refreshes on the same cagg are safe from deadlock because all
	 * sessions scan the same index in ascending lowest_modified_value order,
	 * ensuring exclusive tuple locks are always acquired in a consistent order.
	 * However, we have this problem:
	 * S1:  in txn3 materializing ranges  [ 40, 60 ].
	 *      so it will read rows from mat. inv log.
	 *      delete + insert rows into cagg's mat hypertable
	 *      delete row from mat inv log
	 * S2: in txn2 reading invalidation logs in [ 60 80]
	 *     this will read all the logs starting from the beginning
	 *      and < 80 so that it can process overlaps.
	 * S1: locks row for tuple 45
	 *                              S2 : acquires ShareUpdateExclusiveLock
	 *                              S2:  waits for lock for tuple 45
	 * S1: needs to create a new chunk in mat hypertable
	 *     blocks on S2's ShareUpdateExclusiveLock
	 *     so we have a deadlock
	 * To prevent that in txn2 don't block on locks for mat inv log rows.
	 * it is being concurrently processed by another session.
	 * use waitpolicy = LockWaitSlip
	 */

	MemoryContextReset(state->per_tuple_mctx);

	/* Process all invalidations for the continuous aggregate */
	ts_scanner_foreach(&iterator)
	{
		TupleInfo *ti = ts_scan_iterator_tuple_info(&iterator);
		MemoryContext oldmctx;
		Invalidation logentry;

		oldmctx = MemoryContextSwitchTo(state->per_tuple_mctx);
		invalidation_entry_set_from_cagg_invalidation(&logentry,
													  ti,
													  state->cagg->partition_type,
													  state->cagg->bucket_function);

		/* Skip entries completely before the refresh window — nothing to do */
		if (logentry.greatest_modified_value < refresh_window->start)
		{
			MemoryContextSwitchTo(oldmctx);
			MemoryContextReset(state->per_tuple_mctx);
			continue;
		}

		if (!IsValidInvalidation(&mergedentry))
		{
			mergedentry = logentry;
		}
		else if (invalidation_entry_try_merge(&mergedentry,
											  &logentry,
											  state->cagg->data.granular_refresh_enabled))
		{
			/*
			 * The previous and current invalidation were merged into
			 * one entry (i.e., they overlapped or were adjacent).
			 */
			ts_catalog_delete_tid_only(state->cagg_log_rel, &logentry.tid);
		}
		else
		{
			inner_range = cut_cagg_invalidation_and_compute_inner_range(state,
																		refresh_window,
																		&mergedentry,
																		&inner_range);
			mergedentry = logentry;
		}

		MemoryContextSwitchTo(oldmctx);
		MemoryContextReset(state->per_tuple_mctx);
	}

	ts_scan_iterator_close(&iterator);

	/* Handle the last (merged) invalidation */
	if (IsValidInvalidation(&mergedentry))
	{
		inner_range = cut_cagg_invalidation_and_compute_inner_range(state,
																	refresh_window,
																	&mergedentry,
																	&inner_range);
	}

	/* Write the last (merged) inner range back to the cagg invalidation log */
	insert_cagg_invalidation_entry(state->cagg_log_rel, &inner_range);
}

static void
cagg_invalidation_state_init(ContinuousAggInvalidationState *state, const ContinuousAgg *cagg)
{
	state->cagg = cagg;
	state->cagg_log_rel = open_cagg_table(CAGG_INVALIDATION_LOG, RowExclusiveLock);
	state->per_tuple_mctx = AllocSetContextCreate(CurrentMemoryContext,
												  "Materialization invalidations",
												  ALLOCSET_DEFAULT_SIZES);
	state->snapshot = RegisterSnapshot(GetTransactionSnapshot());
}

static void
cagg_invalidation_state_cleanup(const ContinuousAggInvalidationState *state)
{
	table_close(state->cagg_log_rel, NoLock);
	UnregisterSnapshot(state->snapshot);
	MemoryContextDelete(state->per_tuple_mctx);
}

static void
hypertable_invalidation_state_init(HypertableInvalidationState *state, int32 hypertable_id,
								   Oid dimtype, const ContinuousAggInfo *all_caggs)
{
	state->hypertable_id = hypertable_id;
	state->dimtype = dimtype;
	state->all_caggs = all_caggs;
	state->cagg_log_rel = open_cagg_table(CAGG_INVALIDATION_LOG, RowExclusiveLock);
	state->per_tuple_mctx = AllocSetContextCreate(CurrentMemoryContext,
												  "Hypertable invalidations",
												  ALLOCSET_DEFAULT_SIZES);
	state->snapshot = RegisterSnapshot(GetTransactionSnapshot());
}

static void
hypertable_invalidation_state_cleanup(const HypertableInvalidationState *state)
{
	table_close(state->cagg_log_rel, NoLock);
	UnregisterSnapshot(state->snapshot);
	MemoryContextDelete(state->per_tuple_mctx);
}

/*
 * How many of the newest generations the collector leaves alone, counted down
 * from the highest seqnum the tracking table holds.
 */
#define TRACKING_CLEANUP_HEADROOM 1

/*
 * Reclaim tenant-tracking rows that has no associated invalidations (i.e.,
 * invalidations with the same seqnum)
 *
 * An invalidation can still land after its seqnum looked dead -- a DML that
 * started in an older generation and commits later. Its tracking rows are gone
 * by then, so that range takes a full refresh instead of a granular one.
 *
 * TODO: this assumes a single granular-tracking cagg per hypertable, so the
 * refreshing cagg's own log settles liveness for the per-hypertable tracking
 * rows. With several such caggs liveness has to be established across all of
 * their logs -- otherwise this cagg's GC deletes rows a sibling still needs.
 */
void
invalidation_garbage_collect_tenant_tracking(const ContinuousAgg *cagg)
{
	/*
	 * The headroom bound keeps the top of the seqnum range out of the result even
	 * when it looks dead. A DML publishes its tenant hint at pre-commit, so a
	 * flush can persist tracking rows for a generation whose invalidation has not
	 * committed yet. Leaving headroom at the top gives those invalidations time to land.
	 *
	 * The bound is the tracking table's own highest seqnum, which the planner
	 * answers with one more index lookup, rather than the tracker's in-memory
	 * generation.
	 */
	const char *sql =
		"SELECT d.seqnum FROM ("
		"  SELECT DISTINCT seqnum"
		"    FROM _timescaledb_catalog.continuous_aggs_tenant_tracking"
		"   WHERE hypertable_id = $1) d"
		" WHERE d.seqnum <= (SELECT max(seqnum)"
		"    FROM _timescaledb_catalog.continuous_aggs_tenant_tracking"
		"   WHERE hypertable_id = $1) - $3"
		" AND NOT EXISTS ("
		"  SELECT 1"
		"    FROM _timescaledb_catalog.continuous_aggs_materialization_invalidation_log"
		"   WHERE materialization_id = $2 AND seqnum = d.seqnum)"
		" AND NOT EXISTS ("
		"  SELECT 1"
		"    FROM _timescaledb_catalog.continuous_aggs_hypertable_invalidation_log"
		"   WHERE hypertable_id = $1 AND seqnum = d.seqnum)";
	Oid argtypes[3] = { INT4OID, INT4OID, INT4OID };
	Datum args[3];
	int32 hypertable_id = cagg->data.raw_hypertable_id;
	MemoryContext caller_cxt = CurrentMemoryContext;
	int32 *dead;
	uint64 ndead;
	uint64 i;

	/*
	 * Only a cagg doing granular refresh has tracking rows to reclaim, and only
	 * its own log can keep them alive. A cagg that does not opt in has its
	 * entries stamped seqnum 0, which no tracking row carries.
	 */
	if (!cagg->data.granular_refresh_enabled)
	{
		return;
	}

	args[0] = Int32GetDatum(hypertable_id);
	args[1] = Int32GetDatum(cagg->data.mat_hypertable_id);
	args[2] = Int32GetDatum(TRACKING_CLEANUP_HEADROOM);

	if (SPI_connect() != SPI_OK_CONNECT)
	{
		elog(ERROR, "could not connect to SPI to reclaim tenant tracking");
	}

	/*
	 * read_only = false so SPI advances the command counter and takes a fresh
	 * snapshot. This is required, not incidental: the caller has just moved the
	 * hypertable log into this cagg's log in the very same transaction, and we want
	 * to include those invalidations in determining a seqnum's liveness.
	 *
	 * A seqnum of 0 or NULL in the log matches nothing here, which is right: no
	 * tracking row carries either, so neither can keep one alive.
	 */
	if (SPI_execute_with_args(sql, 3, argtypes, args, NULL, false /* read_only */, 0) !=
		SPI_OK_SELECT)
	{
		elog(ERROR, "could not scan for reclaimable tenant tracking");
	}

	ndead = SPI_processed;
	dead = (ndead > 0) ? (int32 *) MemoryContextAlloc(caller_cxt, ndead * sizeof(int32)) : NULL;

	/* Copy out before the result is released. seqnum is NOT NULL. */
	for (i = 0; i < ndead; i++)
	{
		bool isnull;
		Datum datum = SPI_getbinval(SPI_tuptable->vals[i], SPI_tuptable->tupdesc, 1, &isnull);

		Assert(!isnull);
		dead[i] = DatumGetInt32(datum);
	}

	SPI_finish();

	/*
	 * Deletes go through the catalog API, a whole seqnum
	 * at a time.
	 */
	for (i = 0; i < ndead; i++)
	{
		ts_cagg_tenant_tracking_delete_by_seqnum_only(hypertable_id, dead[i]);
	}

	if (ndead > 0)
	{
		/* Publish the whole reclamation to later commands in a single step. */
		CommandCounterIncrement();
	}

	elog(DEBUG1,
		 "Continuous aggregate \"%s\": reclaimed tenant tracking for " UINT64_FORMAT
		 " generation(s)",
		 NameStr(cagg->data.user_view_name),
		 ndead);

	if (dead != NULL)
	{
		pfree(dead);
	}
}

/*
 * Move invalidations for a single hypertable from hypertable invalidation log
 * to materialization invalidation log. This will move *all* hypertable
 * invalidations for the hypertable to the associated continuous aggregates.
 */
void
invalidation_process_hypertable_log(int32 hypertable_id, Oid dimtype)
{
	HypertableInvalidationState state;
	const ContinuousAggInfo all_caggs = ts_continuous_agg_get_all_caggs_info(hypertable_id);

	hypertable_invalidation_state_init(&state, hypertable_id, dimtype, &all_caggs);
	move_invalidations_from_hyper_to_cagg_log(&state);
	hypertable_invalidation_state_cleanup(&state);
}

void
invalidation_process_cagg_log(const ContinuousAgg *cagg, const InternalTimeRange *refresh_window)
{
	ContinuousAggInvalidationState state;

	cagg_invalidation_state_init(&state, cagg);
	process_cagg_invalidations_for_refresh(&state, refresh_window);
	cagg_invalidation_state_cleanup(&state);
}

/*
 * Scanner filter that excludes cagg invalidation log entries whose
 * greatest_modified_value extends beyond the refresh window end.
 * The exclusive window_end (int64 *) is passed as data.
 */
static ScanFilterResult
cagg_invalidation_window_end_filter(const TupleInfo *ti, void *data)
{
	int64 window_end = *(const int64 *) data;
	bool isnull;
	Datum greatest =
		slot_getattr(ti->slot,
					 Anum_continuous_aggs_materialization_invalidation_log_greatest_modified_value,
					 &isnull);

	Assert(!isnull);
	return DatumGetInt64(greatest) < window_end ? SCAN_INCLUDE : SCAN_EXCLUDE;
}

/*
 * Read all cagg invalidation log entries that fall entirely within
 * [refresh_window->start, refresh_window->end) — i.e., entries written by
 * Txn 2 as "ready to materialize" — collect them into an InvalidationStore,
 * and delete them from the log.
 *
 * Txn 2 cuts all log entries to be either fully inside or fully outside the
 * refresh window.  However, between Txn 2 and Txn 3, a concurrent session's
 * Txn 1 (invalidation_process_hypertable_log) may insert new cagg log entries
 * that partially overlap the window and have not been cut.  The scan
 * skips those entries.
 *
 * The (materialization_id, lowest_modified_value) index is used for a range
 * scan scoped to [window_start, window_end).  The greatest_modified_value
 * check is applied as a heap-side filter via the scanner's filter callback.
 *
 * Returns an InvalidationStore with the collected entries, or NULL if no
 * entries were found.
 *
 * NOTE: Txn2 can process only entries strictly falling within its refresh window.
 * This is because a concurrent transaction could be processing an adjacent ranges.
 * So Txn2 can no longer attempt to work on entries outside its refresh window.
 * When this transaction commits, all new entries written by it will be visible to
 * refresh processes in Txn 3.
 *
 */
InvalidationStore *
collect_and_delete_cagg_invalidations_in_window(const ContinuousAgg *cagg,
												const InternalTimeRange *refresh_window, bool force)
{
	ScanIterator iterator;
	int64 window_end = refresh_window->end;
	InvalidationStore *store = NULL;
	TupleDesc tupdesc = NULL;
	Tuplestorestate *tupstore = NULL;

	if (force)
	{
		/*
		 * Forced refresh: pre-build a store covering the entire window.
		 * Log entries will be deleted below but not collected into the store.
		 */
		Relation rel = open_cagg_table(CAGG_INVALIDATION_LOG, AccessShareLock);
		tupdesc = CreateTupleDescCopy(RelationGetDescr(rel));
		table_close(rel, AccessShareLock);

		int64 inclusive_end = ts_time_saturating_sub(refresh_window->end, 1, refresh_window->type);
		/* Forced refresh is not tenant-tracked: seqnum 0 -> NULL. */
		HeapTuple forced_tuple = create_cagg_invalidation_tup(tupdesc,
															  cagg->data.mat_hypertable_id,
															  refresh_window->start,
															  inclusive_end,
															  0);
		tupstore = tuplestore_begin_heap(false, false, work_mem);
		tuplestore_puttuple(tupstore, forced_tuple);
		heap_freetuple(forced_tuple);
	}

	cagg_invalidations_scan_by_hypertable_init(&iterator,
											   cagg->data.mat_hypertable_id,
											   RowExclusiveLock,
											   window_end);
	/* Add lower bound: only entries whose start is inside the refresh window */
	ts_scan_iterator_scan_key_init(
		&iterator,
		Anum_continuous_aggs_materialization_invalidation_log_idx_lowest_modified_value,
		BTGreaterEqualStrategyNumber,
		F_INT8GE,
		Int64GetDatum(refresh_window->start));
	/* Filter out entries that extend beyond the window end */
	iterator.ctx.filter = cagg_invalidation_window_end_filter;
	iterator.ctx.data = &window_end;

	ts_scanner_foreach(&iterator)
	{
		TupleInfo *ti = ts_scan_iterator_tuple_info(&iterator);

		if (!force)
		{
			if (tupdesc == NULL)
			{
				/* Initialize the tuplestore on first match */
				tupstore = tuplestore_begin_heap(false, false, work_mem);
				tupdesc = CreateTupleDescCopy(RelationGetDescr(ti->scanrel));
			}

			bool should_free;
			HeapTuple tuple = ts_scanner_fetch_heap_tuple(ti, false, &should_free);
			tuplestore_puttuple(tupstore, tuple);
			if (should_free)
			{
				heap_freetuple(tuple);
			}
		}

		ts_catalog_delete_tid_only(ti->scanrel, ts_scanner_get_tuple_tid(ti));
	}
	ts_scan_iterator_close(&iterator);

	if (tupstore != NULL)
	{
		store = palloc(sizeof(InvalidationStore));
		store->tupstore = tupstore;
		store->tupdesc = tupdesc;
	}

	return store;
}

void
invalidation_store_free(InvalidationStore *store)
{
	FreeTupleDesc(store->tupdesc);
	tuplestore_end(store->tupstore);
	pfree(store);
}

bool
invalidation_hypertable_has_invalidations(int32 hyper_id)
{
	bool found = false;
	ScanIterator iterator;
	hypertable_invalidation_scan_init(&iterator, hyper_id, AccessShareLock);
	iterator.ctx.limit = 1; /* we only need to know if there is at least one */

	ts_scan_iterator_start_scan(&iterator);
	if (ts_scan_iterator_next(&iterator))
	{
		found = true;
	}
	ts_scan_iterator_close(&iterator);

	return found;
}

bool
invalidation_cagg_has_pending_mat_ranges(ContinuousAgg *cagg)
{
	bool found = false;
	int32 cagg_hyper_id = cagg->data.mat_hypertable_id;

	ScanIterator iterator = ts_scan_iterator_create(CONTINUOUS_AGGS_MATERIALIZATION_RANGES,
													AccessShareLock,
													CurrentMemoryContext);
	iterator.ctx.index = catalog_get_index(ts_catalog_get(),
										   CONTINUOUS_AGGS_MATERIALIZATION_RANGES,
										   CONTINUOUS_AGGS_MATERIALIZATION_RANGES_IDX);
	ts_scan_iterator_scan_key_init(&iterator,
								   Anum_continuous_aggs_materialization_ranges_materialization_id,
								   BTEqualStrategyNumber,
								   F_INT4EQ,
								   Int32GetDatum(cagg_hyper_id));
	iterator.ctx.limit = 1; /* we only need to know if there is at least one */

	ts_scan_iterator_start_scan(&iterator);
	if (ts_scan_iterator_next(&iterator))
	{
		found = true;
	}
	ts_scan_iterator_close(&iterator);

	return found;
}

bool
invalidation_cagg_has_invalidations(ContinuousAgg *cagg)
{
	bool found = false;
	int32 cagg_hyper_id = cagg->data.mat_hypertable_id;

	ScanIterator iterator;
	cagg_invalidations_scan_by_hypertable_init(&iterator,
											   cagg_hyper_id,
											   AccessShareLock,
											   PG_INT64_MAX);

	int64 watermark = ts_cagg_watermark_get(cagg_hyper_id);
	ts_scanner_foreach(&iterator)
	{
		TupleInfo *ti;
		Invalidation logentry;

		ti = ts_scan_iterator_tuple_info(&iterator);

		invalidation_entry_set_from_cagg_invalidation(&logentry,
													  ti,
													  cagg->partition_type,
													  cagg->bucket_function);
		/* Entries which cannot be invalidations */
		if (logentry.greatest_modified_value == INVAL_NEG_INFINITY ||
			logentry.lowest_modified_value >= watermark)
		{
			continue;
		}
		else
		{
			found = true;
			break;
		}
	}
	ts_scan_iterator_close(&iterator);

	return found;
}

/*
 * Max non-NULL seqnum among rows of `table` whose index-key column `id_attno`
 * equals `id_value`, read via `index`.
 */
static int32
scan_max_seqnum(CatalogTable table, int index, AttrNumber id_attno, int32 id_value,
				AttrNumber seqnum_attno)
{
	int32 max_seqnum = 0;
	ScanIterator iterator = ts_scan_iterator_create(table, AccessShareLock, CurrentMemoryContext);

	iterator.ctx.index = catalog_get_index(ts_catalog_get(), table, index);
	ts_scan_iterator_scan_key_init(&iterator,
								   id_attno,
								   BTEqualStrategyNumber,
								   F_INT4EQ,
								   Int32GetDatum(id_value));

	ts_scanner_foreach(&iterator)
	{
		TupleInfo *ti = ts_scan_iterator_tuple_info(&iterator);
		bool isnull;
		Datum datum;

		/* Debug-only: throw mid-scan (relation ref + buffer pin + snapshot held) to
		 * exercise the tenant-tracker resolver's subtransaction cleanup of
		 * resource-owner resources on a catalog-scan OOM. */
		DEBUG_ERROR_INJECTION("tenant_tracker_seqnum_scan_oom");

		datum = slot_getattr(ti->slot, seqnum_attno, &isnull);

		if (!isnull)
		{
			int32 seqnum = DatumGetInt32(datum);

			if (seqnum > max_seqnum)
			{
				max_seqnum = seqnum;
			}
		}
	}

	ts_scan_iterator_close(&iterator);

	return max_seqnum;
}

/*
 * Highest seqnum durably recorded for a hypertable's granular tracking, used to
 * seed the in-memory tracker's seqnum on first touch after a (re)start so new
 * seqnums do not collide with pre-restart ones.
 *
 * Scans all three durable sources -- the hypertable invalidation log, the
 * materialization invalidation log of each granular-refresh-enabled cagg, and the
 * tenant-tracking catalog -- and takes the max.
 *
 * Note that because we cannot assume any relative ordering of seqnums across the
 * three sources. An invalidations of seqnum X can be processed and stored in the cagg
 * invalidation log before an invalidation of seqnum X-1 is persisted in the hypertable
 * invalidation log. This is because the flusher, which increases seqnum, only waits for
 * tracking writers to finish writing, rather than wait for the DML txn to finish.
 * Similarly, trackings of seqnum X can be flushed either before or
 * after its association validation (of the same seqnum X) is persisted in the hypertable
 * invalidation log.
 */
int32
invalidation_max_seqnum_for_hypertable(int32 hypertable_id)
{
	int32 max_seqnum;
	int32 tenant_max;
	ListCell *lc;
	List *caggs;

	max_seqnum = scan_max_seqnum(CONTINUOUS_AGGS_HYPERTABLE_INVALIDATION_LOG,
								 CONTINUOUS_AGGS_HYPERTABLE_INVALIDATION_LOG_IDX,
								 Anum_continuous_aggs_hypertable_invalidation_log_idx_hypertable_id,
								 hypertable_id,
								 Anum_continuous_aggs_hypertable_invalidation_log_seqnum);

	caggs = ts_continuous_aggs_find_by_raw_table_id(hypertable_id);
	foreach (lc, caggs)
	{
		ContinuousAgg *cagg = lfirst(lc);

		/* TODO: Revisit this after we decided on how we handle seqnums for caggs that opt out of
		   granular refresh while its hypertable has a tracking column. Also related to this is how
		   we handle seqnums in cagg invalidation logs when we disable and re-enable granular
		   refresh for a cagg. */

		if (!cagg->data.granular_refresh_enabled)
		{
			continue;
		}

		int32 mat_max = scan_max_seqnum(
			CONTINUOUS_AGGS_MATERIALIZATION_INVALIDATION_LOG,
			CONTINUOUS_AGGS_MATERIALIZATION_INVALIDATION_LOG_IDX,
			Anum_continuous_aggs_materialization_invalidation_log_idx_materialization_id,
			cagg->data.mat_hypertable_id,
			Anum_continuous_aggs_materialization_invalidation_log_seqnum);

		if (mat_max > max_seqnum)
		{
			max_seqnum = mat_max;
		}
	}
	list_free(caggs);

	tenant_max = ts_cagg_tenant_tracking_max_seqnum(hypertable_id);
	if (tenant_max > max_seqnum)
	{
		max_seqnum = tenant_max;
	}

	return max_seqnum;
}
