name: Start release
on:
  push:
    branches:
      - feat/one-click-release
  workflow_dispatch:
    inputs:
      version:
        description: "Version to use"
        required: true
        type: string


jobs:
  release:
    name: Release mechanisms
    uses: ./github/workflows/release/start.yml
