# Check our codebase for defective programming patterns
name: Coccinelle
"on":
  pull_request:
  push:
    branches:
      - main
      - ?.*.x
jobs:
  coccinelle:
    name: Coccinelle
    runs-on: ubuntu-latest

    steps:
    - name: Install Linux Dependencies
      timeout-minutes: 15
      run: |
        yes | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
        sudo apt-get update
        sudo apt-get -y install --no-install-recommends coccinelle postgresql-server-dev-18

    - name: Checkout TimescaleDB
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Run coccinelle
      run: |
        ./scripts/coccinelle.sh

    - name: Save coccinelle.diff
      if: always()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: coccinelle.diff
        path: coccinelle.diff

