name: Create minor release branch
on:
  workflow_dispatch:

# The workflow needs the permission to push branches
permissions:
  contents: write

jobs:
  create-minor-release-branch:
    name: Create minor release branch
    runs-on: ubuntu-latest

    steps:
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install pip

      - name: Install Python Dependencies
        run: |
          pip install PyGithub requests

      - name: Checkout TimescaleDB
        uses: actions/checkout@v4

      - name: Run the minor-release branch creation Script
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_AUTOMATION_TOKEN }}
        run: |
          git remote --verbose
          scripts/release/create_minor_release_branch.sh
