name: "Release: Build packages"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build_docker_image:
    name: Build Docker image
    uses: timescale/timescaledb-docker/.github/workflows/docker-image.yml@main
    with:
      version: ${{ inputs.version }}
      tag_latest: true
      registry: prod
    secrets: inherit

  docker_image_cooldown:
    name: Docker image propagation cooldown
    needs: build_docker_image
    runs-on: runs-on/fleet=linux-2cpu/env=prod
    steps:
      - name: Wait for image propagation
        run: sleep 15

  test_docker_images:
    name: Test Docker images
    needs: docker_image_cooldown
    uses: ./.github/workflows/docker-images.yaml

  build_apt_packages:
    name: Build APT packages
    uses: timescale/release-build-scripts/.github/workflows/timescaledb-apt.yml@main
    with:
      version: ${{ inputs.version }}
      upload-artifacts: true
    secrets: inherit

  apt_packages_cooldown:
    name: APT package propagation cooldown
    needs: build_apt_packages
    runs-on: runs-on/fleet=linux-2cpu/env=prod
    steps:
      - name: Wait for package propagation
        run: sleep 15

  test_apt_packages:
    name: Test APT packages
    needs: apt_packages_cooldown
    uses: ./.github/workflows/apt-packages.yaml

  build_rpm_packages:
    name: Build RPM packages
    uses: timescale/release-build-scripts/.github/workflows/timescaledb-rpm.yml@main
    with:
      version: ${{ inputs.version }}
      upload-artifacts: true
    secrets: inherit

  rpm_package_cooldown:
    name: RPM package propagation cooldown
    needs: build_rpm_packages
    runs-on: runs-on/fleet=linux-2cpu/env=prod
    steps:
      - name: Wait for package propagation
        run: sleep 15

  test_rpm_packages:
    name: Test RPM packages
    needs: rpm_package_cooldown
    uses: ./.github/workflows/rpm-packages.yaml

  build_homebrew_packages:
    name: Build Homebrew package
    uses: timescale/release-build-scripts/.github/workflows/timescaledb-homebrew.yml@main
    with:
      version: ${{ inputs.version }}
      upload-artifacts: true
    secrets: inherit

  homebrew_package_cooldown:
    name: Homebrew package propagation cooldown
    needs: build_homebrew_packages
    runs-on: runs-on/fleet=linux-2cpu/env=prod
    steps:
      - name: Wait for package propagation
        run: sleep 15

  test_homebrew_package:
    name: Test Homebrew package
    needs: homebrew_package_cooldown
    uses: ./.github/workflows/homebrew.yaml
