name: "Run nightly tests on minor version branch"

"on":
  schedule:
    # run daily at 00:00 on the old minor version branch
    - cron: '0 0 * * *'
    - cron: '0 22 * * SAT'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout TimescaleDB
        uses: actions/checkout@v4

      - name: Set env var OLD_MINOR_VERSION_BRANCH
      shell: bash
      run: |
        CURRENT_MAIN_VERSION=$(head -1 version.config | cut -d ' ' -f 3 | cut -d '-' -f 1)
        CURRENT_MINOR_VERSION=$(echo $CURRENT_MAIN_VERSION | cut -d '.' -f 2)
        OLD_MINOR_VERSION=$(echo $CURRENT_MAIN_VERSION | sed -e "s/$CURRENT_MINOR_VERSION/$(($CURRENT_MINOR_VERSION - 1))/g")
        echo "OLD_MINOR_VERSION_BRANCH="${OLD_MINOR_VERSION/%.0/.x}"" >> $GITHUB_ENV

      - name: Run nightly tests
        if: github.event.schedule != '0 22 * * SAT'
        env:
          GH_TOKEN: ${{ secrets.ORG_AUTOMATION_TOKEN }}
        run: |
          gh workflow run linux-32bit-build-and-test.yaml -R timescale/timescaledb -f branch="$OLD_MINOR_VERSION_BRANCH"
          gh workflow run linux-build-and-test.yaml -R timescale/timescaledb -f branch="$OLD_MINOR_VERSION_BRANCH"
          gh workflow run rpm-packages.yaml -R timescale/timescaledb -f branch="$OLD_MINOR_VERSION_BRANCH"
          gh workflow run sanitizer-build-and-test.yaml -R timescale/timescaledb -f branch="$OLD_MINOR_VERSION_BRANCH"
          gh workflow run windows-build-and-test.yaml -R timescale/timescaledb -f branch="$OLD_MINOR_VERSION_BRANCH"
          gh workflow run snapshot-abi.yaml -R timescale/timescaledb -f branch="$OLD_MINOR_VERSION_BRANCH"
          gh workflow run abi.yaml -R timescale/timescaledb -f branch="$OLD_MINOR_VERSION_BRANCH"
          gh workflow run apt-arm-packages.yaml -R timescale/timescaledb -f branch="$OLD_MINOR_VERSION_BRANCH"
          gh workflow run apt-packages.yaml -R timescale/timescaledb -f branch="$OLD_MINOR_VERSION_BRANCH"
          gh workflow run docker-images.yaml -R timescale/timescaledb -f branch="$OLD_MINOR_VERSION_BRANCH"
          gh workflow run windows-packages.yaml -R timescale/timescaledb -f branch="$OLD_MINOR_VERSION_BRANCH"
          gh workflow run homebrew.yaml -R timescale/timescaledb -f branch="$OLD_MINOR_VERSION_BRANCH"
          gh workflow run libfuzzer.yaml -R timescale/timescaledb -f branch="$OLD_MINOR_VERSION_BRANCH"
          gh workflow run sqlsmith.yaml -R timescale/timescaledb -f branch="$OLD_MINOR_VERSION_BRANCH"

      - name: Run weekly coverity tests
        if: github.event.schedule != '0 0 * * *'
        env:
          GH_TOKEN: ${{ secrets.ORG_AUTOMATION_TOKEN }}
        run: |
          gh workflow run coverity.yaml -R timescale/timescaledb -f branch="$OLD_MINOR_VERSION_BRANCH"
