# Test our shell scripts for bugs
name: Shellcheck
"on":
  pull_request:
  push:
    branches:
      - main
      - ?.*.x
jobs:
  check_paths:
    runs-on: timescaledb-runner-arm64
    outputs:
      run_ci: >-
        ${{ github.event_name == 'push'
          || (steps.filter.outputs.shell == 'true' && !contains(github.event.pull_request.labels.*.name, 'skip-ci'))
         }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: .github/filters.yaml

  shellcheck:
    name: Shellcheck
    needs: [check_paths]
    if: needs.check_paths.outputs.run_ci == 'true'
    runs-on: timescaledb-runner-arm64

    steps:
    - name: Replace unreliable Azure APT mirror
      run: |
        sudo touch /etc/apt/apt-mirrors.txt
        sudo sed -i.bak -e s,azure.archive.ubuntu,aws.archive.ubuntu,g /etc/apt/apt-mirrors.txt

    - name: Install Linux Dependencies
      timeout-minutes: 15
      run: |
        sudo apt-get update
        sudo apt-get install shellcheck

    - name: Checkout TimescaleDB
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0

    - name: Run shellcheck
      run: scripts/shellcheck-ci.sh

  report_status:
    name: Shellcheck summary
    needs: [check_paths, shellcheck]
    if: always()
    runs-on: timescaledb-runner-arm64
    steps:
      - run: |
          # If the detector failed, or the matrix failed, exit with error
          if [[ "${{ needs.shellcheck.result }}" == "failure" ]]; then
            exit 1
          fi
          echo "All checks passed or were safely skipped."

