\ir ../../main/table_creation.sql
\ir ../../main/cluster_user_triggers.sql
\ir ../../main/node_triggers.sql
\ir ../../main/meta_triggers.sql
\ir ../../main/hypertable_triggers.sql
\ir ../../main/hypertable_replica_triggers.sql
\ir ../../main/distinct_replica_node_triggers.sql
\ir ../../main/field_triggers.sql
\ir ../../main/partitioning.sql
\ir ../../main/schema_info.sql
\ir ../../main/tables.sql
\ir ../../main/partition_replica_triggers.sql
\ir ../../main/chunk_replica_node_index.sql
\ir ../../main/chunk_replica_node_index_triggers.sql
\ir ../../main/chunk_replica_node_triggers.sql
\ir ../../main/chunk_triggers.sql
\ir ../../main/chunk.sql
\ir ../../main/insert.sql

\ir ../../main/ioql.sql
\ir ../../main/ioql_exec_node.sql
\ir ../../main/ioql_result_schema_nonagg.sql
\ir ../../main/ioql_result_schema_agg.sql
\ir ../../main/ioql_schema_info.sql
\ir ../../main/ioql_sql_gen.sql
\ir ../../main/ioql_remote_calls.sql
\ir ../../main/ioql_optimized_agg.sql
\ir ../../main/ioql_sqlgen_cluster_agg.sql
\ir ../../main/ioql_distinct_queries.sql
\ir ../../main/ioql_optimized_nonagg.sql
\ir ../../main/ioql_sqlgen_cluster_nonagg.sql
\ir ../../main/ioql_optimized.sql
